---
title: "Size and age frequencies"
author: "Asa Julien"
date: "August 2, 2016"
output: html_document
---

##Size and age frequencies, FOLLY BEACH COUNTY PARK
```{r, echo=FALSE}
library(FSA)
library(nlstools)
library(ggplot2)
library(lattice)
library(dplyr)

#windows:
fbcp_freq = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Size frequency\\CSV files\\sizeagefreq_fbcp.csv")
#mac:
fbcp_freq = read.csv("~/Documents/Ribbed mussel/Data/Size frequency/CSV files/sizeagefreq_fbcp.csv")

std.err = function(x)
  sd(x)/sqrt(length(x))

#ggplot, by month
fbcp_freq$Month.code = factor(fbcp_freq$Month.code, levels = c("August","September","October","November","December", "January", "February", "March", "April", "May", "June", "July"))

sizeage_plot = ggplot(data = fbcp_freq, aes(x = Length.mm)) + geom_histogram(binwidth = 5) + facet_grid(~Month.code) + theme_bw() + labs(x = "Length (mm)", y="Frequency")

sizeage_plot

#percent hists 
mydata = fbcp_freq %>%
  select(Length.mm, Month.code)
  colnames(mydata) = c("Length", "Month")
  
pcent = ggplot(data = mydata, aes(x = Length)) + geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Month) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)") 

pcent + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = seq(0, 20, 5))

#Percent by month
tot_muss = fbcp_freq %>%
  group_by(Month.code) %>%
  summarise(length(Length.mm))
colnames(tot_muss) = c("Month", "Total")

tot_muss$Juvs =  tapply(fbcp_freq$Length.mm[fbcp_freq$Length.mm <= 17], fbcp_freq$Month.code[fbcp_freq$Length.mm <= 17], length) #17 mm = length at age 0; 43 mm length at age 1 (so <43); they tell different stories. I think recruits are going to be small, so there's a lot to be said for keeping it at 17.
  
tot_muss$perjuvs = tot_muss$Juvs/tot_muss$Total * 100

ggplot(tot_muss, aes(Month, perjuvs, group = 1)) + geom_point() + geom_line() + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=10), axis.text.y = element_text(size = 15)) + labs(x = "", y="Percent of all individuals") + scale_y_continuous(limits = c(0, 7))


#Average percent by month, a bit convoluted
by_quad = fbcp_freq %>%
  group_by(Quadrat.identifier, Month.code) %>%
  select(Quadrat.identifier, Month.code, Length.mm, Growth.bands) %>%
  summarise(muss = length(Length.mm))

se_juv = fbcp_freq %>%
  group_by(Quadrat.identifier, Month.code) %>%
  select(Quadrat.identifier, Month.code, Length.mm, Growth.bands) %>%
  summarise(juvs = length(Growth.bands[Length.mm<=17])) 

df_juvs = data.frame(Month = se_juv$Month.code, Juvs = se_juv$juvs/by_quad$muss * 100)

av_juvs = df_juvs %>%
  group_by(Month) %>%
  summarise(mn_j = mean(Juvs), se_j = std.err(Juvs))

ggplot(av_juvs, aes(Month, mn_j, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymin = mn_j - se_j, ymax = mn_j + se_j))

summary(aov(df_juvs$Juvs ~ df_juvs$Month))

#percent above/below size range
length(fbcp_freq$Length.mm[fbcp_freq$Length.mm >= 76.2])/length(fbcp_freq$Length.mm)

```


##Von Bertalanfyy FOLLY BEACH COUNTY PARK
```{r, echo=FALSE}
#von Bertalanffy, FSA package

#get rid of NAs
fbcp.site = fbcp_freq %>%
  select(Quadrat.identifier, Length.mm, Growth.bands) %>%
  na.omit() 

von.length.fbcp = fbcp.site$Length.mm
von.age.fbcp = fbcp.site$Growth.bands

#estimating the parameters (L infinity, K, t0)
svTypical.fbcp = vbStarts(von.length.fbcp ~ von.age.fbcp, plot = TRUE)
unlist(svTypical.fbcp) 
svTypical.fbcp

svTypical.fbcp = list(Linf = 113.79, K = 0.28, t0 = -0.62) #using same Linf variable - CAREFUL
svTypical.fbcp

#nls and model

vbTypical.fbcp = von.length.fbcp ~ Linf * (1 - exp(-K * (von.age.fbcp - t0)))
fitTypical.fbcp = nls(vbTypical.fbcp, start = svTypical.fbcp)
fitPlot(fitTypical.fbcp, xlab = "Number of growth bands", ylab = "Length (mm)", main = "", cex.axis = 1.2, cex.lab = 1.4, font.lab = 2)
overview(fitTypical.fbcp) #It kind of looks like a cubic function right now...


#CHECK ASSUMPTIONS! Look all right to me
residPlot(fitTypical.fbcp)
hist(residuals(fitTypical.fbcp),main="")

#confidence intervals via bootstrapping
boot_df = na.omit(fbcp_freq[, c(6,7)])
colnames(boot_df) = c("boot_length", "boot_age")
boot_fbcp <- as.formula(boot_length ~ boot_Linf * (1 - exp(-boot_K * (boot_age - boot_t0))))
boot_nls1 <- nls(boot_fbcp, start = list(boot_Linf = 113.79, boot_K = 0.28, boot_t0 = -0.62), data = boot_df)
boot_strap1 <- nlsBoot(boot_nls1, niter = 999)
plot(boot_strap1)
plot(boot_strap1, type = "boxplot", ask = FALSE)
summary(boot_strap1)

confint(boot_strap1, plot = TRUE)

htest(boot_strap1, "boot_K", 0.36, "less") #not sure what this accomplishes

ests = boot_strap1$coefboot
pv = ests[,"boot_Linf"]*(1-exp(-ests[,"boot_K"]*(8-ests[,"boot_t0"]))) #exampple at age 8
quantile(pv,c(0.025,0.975))

#confidence interval
ages2plot <- 0:18
fitPlot(fitTypical.fbcp,xlab="Age (growth bands)",ylab="Total Length (mm)",xlim=range(ages2plot),main="")
LCI <- UCI <- numeric(length(ages2plot))

for (i in 1:length(ages2plot)) {
pv <- ests[,"boot_Linf"]*(1-exp(-ests[,"boot_K"]*(ages2plot[i]-ests[,"boot_t0"])))
LCI[i] <- quantile(pv,0.025)
UCI[i] <- quantile(pv,0.975)
}
lines(UCI~ages2plot,type="l",col="blue",lwd=2,lty=2)
lines(LCI~ages2plot,type="l",col="blue",lwd=2,lty=2)


boxplot(von.length.fbcp ~ von.age.fbcp)

#predict lengths for age
pred_age = data.frame(von.age.fbcp = rep(seq(0, 15, 1),2))
pred_age$response = predict(fitTypical.fbcp, newdata = pred_age, type = 'reponse')
plot(pred_age$response ~ pred_age$von.age.fbcp)
#0 bands = 17 mm
#3 bands = 74 mm 
#8 bands = 100 mm
```


#Average ages, sizes by month (subset of data)
```{r, echo=FALSE}
av.age = fbcp_freq %>%
  select(Month.code, Growth.bands) %>%
  group_by(Month.code) %>%
  summarise(mean(na.omit(Growth.bands)))

se.age = fbcp_freq %>%
  select(Month.code, Growth.bands) %>%
  group_by(Month.code) %>%
  summarise(std.err(na.omit(Growth.bands)))


#mean lengths and ages
mn.lengths.fbcp = fbcp_freq %>%
  group_by(Month.code) %>%
  summarise(mean(Length.mm), std.err(Length.mm), mean(na.omit(Growth.bands)), std.err(na.omit(Growth.bands)))
colnames(mn.lengths.fbcp) = c("Month", "Length", "SE.length", "Age", "SE.age")

mn.lengths.fbcp

#plots
mn.lengths.fbcp$Month<-factor(mn.lengths.fbcp$Month, levels = c("August","September","October","November","December", "January", "February", "March", "April", "May", "June", "July")) #Ordering the months

limits.size <- aes(ymax = mn.lengths.fbcp$Length + mn.lengths.fbcp$SE.length, ymin = mn.lengths.fbcp$Length - mn.lengths.fbcp$SE.length)

limits.age = aes(ymax = mn.lengths.fbcp$Age + mn.lengths.fbcp$SE.age, ymin = mn.lengths.fbcp$Age - mn.lengths.fbcp$SE.age)

p.size <- ggplot(mn.lengths.fbcp, aes(Month, Length))
p.size + geom_point(stat = "identity") + geom_errorbar(limits.size, width=0.25) + labs(x="Month",y="Length (mm)")

p.age = ggplot(mn.lengths.fbcp, aes(Month, Age))
p.age + geom_point(stat = "identity") + geom_errorbar(limits.age, width=0.25) + labs(x="Month",y="Growth bands")
```


#Density FBCP
```{r, echo=FALSE}
den.fbcp = fbcp_freq %>%
  group_by(Month.code, Quadrat.identifier) %>%
  summarise(length(Length.mm))

den.fbcp$size = 0.0625
den.fbcp$size[den.fbcp$Quadrat.identifier == "8a"] = 0.04

den.fbcp$density = den.fbcp$`length(Length.mm)`/den.fbcp$size
colnames(den.fbcp) = c("Month", "QuadID", "Musselcount", "Quadsize", "Density")
den.fbcp$Status = rep("Folly")

den.fbcp$Date = den.fbcp$Month

##barplots of average densities:
df.density = den.fbcp %>%
  group_by(Month) %>%
  summarise(mean(Density),std.err(Density))
colnames(df.density)<-c("Month","Density","SE.den")

p.density <- ggplot(df.density,aes(x=Month,y=Density),position="dodge")
p.density + geom_point(stat="identity") + geom_errorbar(aes(ymax=Density+SE.den,ymin=Density-SE.den), width=0.25) + labs(x=expression(Month),y=expression(Density~(individuals~m^{-2})))

#NOT SURE IF THIS IS A SIGNAL OR DUE TO SAMPLING
```


----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
