---
title: "Abundance_diversity_analysis"
author: "Asa Julien"
date: "November 30, 2016"
output: html_document
---
##analyzing abundance
```{r, echo=FALSE}

#this works:
new.df<-read.csv("C:\\users\\juliena\\desktop\\data\\drop net\\csv files\\Diversity_abundance.csv")

Nekton.count<-new.df$Abundance....nekton.
Treatment.count<-new.df$Treatment
Log.count<-log(Nekton.count+1)
Date.newdf<-new.df$Date
Month.newdf<-new.df$Month
trap.no<-as.factor(new.df$Trap.number)
pairing.count<-new.df$Pairing
sal.count<-new.df$Salinity.ppt
temp.count<-new.df$Temperature.C
do2<-new.df$dO2.pascals
tide.count <- new.df$Tidal.height.Charleston.Harbor.water.level..m.
richness.count <- new.df$Species.richness

test.x <- glm(Nekton.count~sal.count + temp.count + Treatment.count + Date.newdf + Treatment.count:Date.newdf) #Is this correct? Order matters for the aov function... log transformation +1 helps with residuals
summary(test.x)
Anova(test.x) #this may be the one to use... what is the difference between type i/ii/iii ss?
plot(test.x)

#species richness


#anova comparison---------------------------------------------------------------------
aov.abundance<-aov(Nekton.count~Treatment.count)
summary(aov.abundance) #NSD so far.
plot(aov.abundance) #residuals not normally distributed, yet

aov.log.abun<-aov(Log.count~Treatment.count)
summary(aov.log.abun)
plot(aov.log.abun) 

kruskal.abundance<-kruskal.test(Nekton.count~Treatment.count)
summary(kruskal.abundance)
kruskal.abundance

#paired t-test------------------------------------------------------------------------

t.abundance<-t.test(Nekton.count~Treatment.count,paired=T)
t.abundance #check assumptions

#blocking by trap number--------------------------------------------------------------
block.trap<-aov(Nekton.count~Treatment.count+trap.no)
summary(block.trap) #no effect of trap on abundance
plot(block.trap)

##and ancova, abundance by date (warning messages due to only one replicate in July) ------------------------------------------------------

anc.legare<-aov(Nekton.count~Treatment.count*Date.newdf)
summary(anc.legare) #no significant effect of treatment, but there is of date. Keep an eye on those residuals.
plot(anc.legare)

lm.anc.legare<-lm(Nekton.count~Treatment.count*Date.newdf)
summary(lm.anc.legare)
plot(lm.anc.legare)

anc.legare.month<-aov(Nekton.count~Treatment.count*Month.newdf)
summary(anc.legare.month) #significant effect of month, residuals could be better.
plot(anc.legare.month)

#salinity and temperature - is this formula correct? Also think AICs
sal.temp<-aov(Nekton.count~Treatment.count*Month.newdf+sal.count+temp.count+tide.count)
summary(sal.temp) #significant effect of month, residuals could be better.
plot(sal.temp)

################## repeated measures anchovy (ancova...)

rep.anc<-aov(Nekton.count~Treatment.count*Date.newdf+Error(pairing.count/Treatment.count)) #or should just Error(pairing.count) be used?
summary(rep.anc)
plot(rep.anc)
#formula kind of from: 
#https://ww2.coastal.edu/kingw/statistics/R-tutorials/repeated.html
#also on:
#https://www.r-bloggers.com/two-way-anova-with-repeated-measures/

#mixed linear model? general linear model

################## Pooled by month, rather than individual date
rep.anc.month<-aov(Nekton.count~Treatment.count*Month.newdf+Error(pairing.count/Treatment.count)) #or should just Error(pairing.count) be used?
summary(rep.anc.month)
plot(rep.anc.month)

###########################################



#means etc. --------------------------------------------------------------------------

std.err<-function(x)
  sd(x)/sqrt(length(x))

mean.abun<-tapply(Nekton.count,Treatment.count,mean)
mean.abun
med.abun<-tapply(Nekton.count,Treatment.count,median)
med.abun
sd.abun<-tapply(Nekton.count,Treatment.count,sd)
sd.abun
se.abun<-tapply(Nekton.count,Treatment.count,std.err)
se.abun
```

##analyzing indices
```{r, echo=FALSE}
require(lattice)
index.legare<-read.csv("C:\\users\\juliena\\desktop\\data\\drop net\\csv files\\Diversity_abundance.csv") #same file as new.df, be careful
shannon<-index.legare$Shannon
Treatment.index<-index.legare$Treatment #Mystery blank treatment level - get rid of this!
simpson<-index.legare$Simpson
inv.sim<-index.legare$Inverse.Simpson
ind.month<-index.legare$Month

aov.shannon<-aov(shannon~Treatment.index)
summary(aov.shannon)
plot(aov.shannon)
bwplot(shannon~Treatment.index)

aov.simp<-aov(simpson~Treatment.index) #doesn't fit assumptions well; heteroscedastic
summary(aov.simp)
plot(aov.simp)
bwplot(simpson~Treatment.index)

aov.inv<-aov(inv.sim~Treatment.index) #problems with inf
summary(aov.inv)
plot(aov.inv)
bwplot(inv.sim~Treatment.index)

#paired t-tests-----------------------------------------------------------------------

t.shan<-t.test(shannon~Treatment.index, paired=T)
t.shan #check assumptions

t.simp<-t.test(simpson~Treatment.index, paired=T)
t.simp

t.inv<-t.test(inv.sim~Treatment.index, paired=T)
t.inv

#ancovas---------------------------------------------------------------------
anc.shan<-aov(shannon~Treatment.index+ind.month)
summary(anc.shan)
plot(anc.shan)

anc.sim<-aov(simpson~Treatment.index+ind.month)
summary(anc.sim)
plot(anc.sim)

anc.inv<-inv.sim~Treatment.index+ind.month
summary(anc.inv)


#Means, errors --------------------------------------------------------------

mean.shan<-tapply(shannon,Treatment.index,mean)
mean.simp<-tapply(simpson,Treatment.index,mean)
mean.inv<-tapply(inv.sim,Treatment.index,mean) #problems w/ blank and infinity
mean.shan
mean.simp
mean.inv

se.shan<-tapply(shannon,Treatment.index,std.err)
se.simp<-tapply(simpson,Treatment.index,std.err)
se.inv<-tapply(inv.sim,Treatment.index,std.err)
se.shan
se.simp
se.inv


```

##POOLED BY SAMPLING DAY
```{r cars}
new.df = read.csv("C:\\users\\juliena\\desktop\\data\\drop net\\csv files\\diversity_abundance.csv")
require(dplyr)

mn.abun = new.df %>% #update when new species are found - or remove all species, I don't like this
  group_by(Date, Treatment, Month) %>%
  select(Date, Treatment, Month, Abundance....nekton., Shannon, Salinity.ppt, Temperature.C, Tidal.height.Charleston.Harbor.water.level..m., Simpson, Species.richness, dO2.mg.L) %>%
  summarise(mean(Abundance....nekton.), mean(Shannon), mean(Salinity.ppt), mean(Temperature.C), mean(Tidal.height.Charleston.Harbor.water.level..m.), mean(Simpson), mean(Species.richness), mean(dO2.mg.L))

colnames(mn.abun)=c("Date","Treatment", "Month", "Abundance", "Shannon", "Salinity", "Temperature","Tidal.ht", "Simpson", "Species richness", "dO2")

mn.abun$Month<-factor(mn.abun$Month, levels = c("July","August","September","October","November","December", "January")) #Ordering the months

abun.anova = aov(Abundance ~ Treatment + Salinity + Temperature + Tidal.ht, data = mn.abun) #WHAT ABOUT SAMPLING DAY
summary(abun.anova)
plot(abun.anova)

abun.lm = lm(Abundance ~ Treatment + Salinity + Temperature +Tidal.ht, data = mn.abun)
summary(abun.lm)
plot(abun.lm)


```

d

```{r pressure, echo=FALSE}
plot(Abundance[Treatment == "Mussels"]~Salinity[Treatment=="Mussels"], data = mn.abun)
plot(Abundance[Treatment == "Spartina"]~Salinity[Treatment=="Spartina"], data = mn.abun)

plot(Abundance[Treatment == "Mussels"]~Temperature[Treatment=="Mussels"], data = mn.abun)
plot(Abundance[Treatment == "Spartina"]~Temperature[Treatment=="Spartina"], data = mn.abun)


summary(lm(Abundance[Treatment == "Mussels"]~Salinity[Treatment=="Mussels"], data = mn.abun))
summary(lm(Abundance[Treatment == "Spartina"]~Salinity[Treatment=="Spartina"], data = mn.abun))

summary(lm(Abundance[Treatment == "Mussels"]~Temperature[Treatment=="Mussels"], data = mn.abun))
summary(lm(Abundance[Treatment == "Spartina"]~Temperature[Treatment=="Spartina"], data = mn.abun))
```

d
##end