---
title: "Abundance and diversity analyses"
output: html_document
---
##Linear models
```{r echo=FALSE}
library(car)
library(nlme)
library(lattice)
library(MASS)
library(dplyr)
library(vegan)

#files
new_df <- read.csv("~/Documents/Ribbed mussel/Data/Drop net/CSV files/Diversity_abundance.csv")
legare_net = read.csv("~/Documents/Ribbed mussel/Data/Drop net/CSV files/Legare.csv")

#models
test_x = lm(log(Abundance + 1) ~ Salinity + Temperature + CharlestonHeight + Treatment + Pairing, data = new_df) 
summary(test_x)
plot(test_x)

test_y = lm(Richness ~ Salinity + Temperature + CharlestonHeight + Treatment + Pairing, data = new_df) 
summary(test_y)
plot(test_y)

test_z = lm(Shannon ~ Salinity + Temperature + CharlestonHeight + Treatment + Pairing, data = new_df) 
summary(test_z)
plot(test_z)

#Mixed effects model
abundance_lme = lme(fixed = Abundance ~ Treatment + Salinity + Temperature + CharlestonHeight, random = ~1 | Date/Pairing, data = new_df)
summary(abundance_lme) #Residuals a little better when log transformed; salinity becomes less "important" when this happens
anova(abundance_lme)
plot(abundance_lme)

```

##Multivariate community composition
```{r, echo = FALSE}
#Community composition and direct ordination (trying both RDA and CCA)
marsh = new_df[, c(seq(7, 17))] #All species except for A. heterochaelis

#rda analysis
marsh_rda
plot(marsh_rda)
plot(marsh_rda, display=c('sp', 'cn'))

marsh_rda2 = rda(sqrt(marsh) ~ Treatment + Condition(Temperature) +
                 Condition(Salinity) + Condition(CharlestonHeight),
                 data = new_df)
plot(marsh_rda2, display=c('sp', 'cn')) #ordiplot

anova(marsh_rda, by='margin', permutations = 2000)
RsquareAdj(marsh_rda)

#cca
marsh_2 = marsh[rowSums(marsh) != 0,]
rowSums(marsh_2)
marsh_cca = cca(marsh_2 ~ Treatment + Temperature + Salinity + CharlestonHeight,                      data = new_df[-c(11, 62, 63, 65, 66, 68, 70),]) #All rows                         have to be greater than zero
marsh_cca
plot(marsh_cca)
anova(marsh_cca, by = 'margin', permutations = 2000) #Different than the rda analysis. Tidal height becomes much less important. Treatment is way more important. Temperature remains fairly important.

```

##NGS (no grass shrimp)
```{r, echo = FALSE}
new_df$abun_ngs = rowSums(new_df[, seq(8, 17)]) #no A. heterochaelis right now because of NAs

#abundance model
test_ngs = lm(log(abun_ngs + 1) ~ Salinity + Temperature + CharlestonHeight + Treatment + Pairing, data = new_df) 
summary(test_ngs)
plot(test_ngs)

#NGS rda analysis
marsh_ngs = new_df[, c(seq(8, 17))] #No P. pugio or A. heterochaelis
ngs_rda = rda(sqrt(marsh_ngs) ~ Treatment + Temperature + Salinity +
              CharlestonHeight, data = new_df) 
#square root transformation makes treatment significant
ngs_rda
RsquareAdj(ngs_rda)
plot(ngs_rda)

anova(ngs_rda, by = 'margin', permutations = 2000)
with(new_df, varpart(sqrt(marsh_ngs), ifelse(Treatment == 'Mussels', 1, 0),  
                     data.frame(Temperature, Salinity), CharlestonHeight))

```


##Elevation data
```{r}
library(lattice)
library(ggplot2)
library(rms)
library(pscl)

ashgrid = read.csv(("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv"))

ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

#All together
ashglm = glm(Mussel.presence ~ Elevation * Block, family = binomial, data = ashgrid)
summary(ashglm)
plot(ashglm)

full_mod = ashglm
main_mod = update(full_mod, . ~ . - Elevation:Block)
elev_mod = update(main_mod, . ~ . - Block)
elev_mod2 = update(elev_mod, . ~ . + I(Elevation^2))
elev_mod3 = update(elev_mod2, . ~ . + I(Elevation^3))
elev_mod4 = update(elev_mod2, . ~ . + Block)
elev_mod5 = update(elev_mod2, . ~ . + Block + Elevation:Block)

anova(full_mod, main_mod, elev_mod, test='LRT')
AIC(full_mod, main_mod, elev_mod)

anova(elev_mod, elev_mod2, elev_mod4, elev_mod5, test='LRT')
AIC(elev_mod, elev_mod2, elev_mod4, elev_mod5) #model 4 is the best?

#add salinity back in - plot both
plot(elev_mod2)
plot(elev_mod4)

#model fits; pseudo r^2
full_r2 = pR2(full_mod)
main_r2 = pR2(main_mod)
mod_r2 = pR2(elev_mod)
mod2_r2 = pR2(elev_mod2)
mod4_r2 = pR2(elev_mod4)
mod5_r2 = pR2(elev_mod5)

#Predicted values and plots
new_data = data.frame(Elevation = seq(0, .8, length.out = 50), Block = rep(c("15-20"), each = 50))
new_data2 = data.frame(Elevation = seq(0, .8, length.out = 50), Block = rep(c("20-25"), each = 50))

plot(Mussel.presence ~ Elevation, data=ashgrid, pch = 20, col = ashgrid$Block, xlab = "Elevation (m)", ylab = "Geukensia demissa presence")
legend(-0.1, 1, unique(ashgrid$Block), col = c("red", "black"), pch = 20)

lines(new_data$Elevation, predict(elev_mod, newdata=new_data, type='response'),
      col='blue')
lines(new_data$Elevation, predict(elev_mod2, newdata=new_data, type='response'),
      col='green')
lines(new_data$Elevation, predict(elev_mod4, newdata=new_data, type='response'),
      col='black')
lines(new_data2$Elevation, predict(elev_mod4, newdata=new_data2, type='response'),
      col='red')

```

