---
title: "Drop net"
author: "Asa Julien"
date: "August 2, 2016"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Sol Legare, general species data
```{r, echo=FALSE}
library(lattice)
library(ggplot2)
library(dplyr)
library(cowplot)

std.err = function(x)
  sd(x)/sqrt(length(x))

#windows
new_df = read.csv("C:\\users\\juliena\\desktop\\data\\drop net\\csv files\\Diversity_abundance.csv")
legare_net = read.csv("C:\\users\\juliena\\desktop\\data\\drop net\\csv files\\legare.csv")

#mac:
new_df = read.csv("~/Documents/Ribbed mussel/Data/Drop net/CSV files/Diversity_abundance.csv")
legare_net = read.csv("~/Documents/Ribbed mussel/Data/Drop net/CSV files/legare.csv")

new_df$Season = c(rep("Fall 2016", 42), rep("Winter 2017", 44), rep("Spring 2017", 24)) #N = 21, 22, 12

#abundance by treatment
with(legare_net, tapply(Species, Treatment, length))
with(legare_net, tapply(Species, Species, length))

```

##Figures
```{r, echo=FALSE}
##tiff("x1.tiff", width = 6, height = 5, units = 'in', res = 300)
#Simple comparisons-------------------------------------------------------
df_compare = new_df %>%
  group_by(Treatment) %>%
  summarise(mean(Abundance), std.err(Abundance), mean(Shannon), std.err(Shannon), mean(Simpson), std.err(Simpson), mean(Richness), std.err(Richness))
colnames(df_compare) <- c("Treatment","Abundance","SE.abun", "Shannon", "SE.shannon", "Simpson", "SE.simpson", "Richness", "SE.richness") #CAREFUL OF NAME OVERLAP! WITH LOWER SECTIONS

compare_abun = ggplot(df_compare, aes(x = Treatment, y = Abundance), position="dodge")
compare_abun + geom_bar(stat = "identity", width = 0.5) + geom_errorbar(aes(ymax = Abundance + SE.abun, ymin = Abundance- SE.abun), width=0.15) + labs(x = expression(), y = expression(Nekton~abundance~(individuals~m^{-2}))) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + ylim(0,15)

compare_shan = ggplot(df_compare, aes(x = Treatment, y = Shannon), position="dodge")
compare_shan + geom_bar(stat = "identity", width = 0.5) + geom_errorbar(aes(ymax = Shannon + SE.shannon, ymin = Shannon - SE.shannon), width=0.15) + labs(x = expression(), y = expression(Shannon~diversity)) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + ylim(0,0.8)

compare_simp = ggplot(df_compare, aes(x = Treatment, y = Simpson),position="dodge")
compare_simp + geom_bar(stat = "identity", width = 0.5) + geom_errorbar(aes(ymax = Simpson + SE.simpson, ymin = Simpson - SE.simpson), width=0.15) + labs(x = expression(), y = expression(Simpson~diversity)) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + ylim(0,0.6)

compare_rich = ggplot(df_compare, aes(x = Treatment, y = Richness), position = "dodge")
compare_rich + geom_bar(stat = "identity", width = 0.5) + geom_errorbar(aes(ymax = Richness + SE.richness, ymin = Richness - SE.richness), width=0.15) + labs(x = expression(), y = expression(Species~richness)) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + ylim(0,3)

##Abundance and diversity, by season #########################################

new_df$Season = factor(new_df$Season, levels = c("Fall 2016", "Winter 2017", "Spring 2017")) #Ordering the months

new_df$SeasonX = factor(new_df$SeasonX, levels = c("Summer 2016", "Fall 2016", "Winter 2017", "Spring 2017", "Summer 2017")) #Ordering the months

##Barplots of averages:
abun_season = new_df %>%
  group_by(Treatment, SeasonX)%>%
  summarise(mean(Abundance), std.err(Abundance))
colnames(abun_season) = c("Treatment", "Season", "Abundance", "SE.abun")

p_seasabun = ggplot(abun_season, aes(Season, Abundance, fill = Treatment)) + geom_bar(position = position_dodge(), stat="identity", colour = 'black') + geom_errorbar(aes(ymax = Abundance + SE.abun, ymin = Abundance-SE.abun), width=0.25, position = position_dodge(.9)) + labs(x = "", y = expression(Nekton~abundance~(individuals~m^{-2}))) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 10, face = "bold", colour = "black"), strip.text = element_text(size = 10, face = "bold", colour = "black"), axis.text.x = element_text(size=8, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) + ylim(0,25) + scale_fill_grey() + theme(legend.title=element_blank()) + scale_y_continuous(expand = c(0,0)) + labs(title = "") + scale_x_discrete(labels = c("Su16", "Fa16", "Wi17", "Sp17", "Su17"))

shan_season = new_df %>%
  group_by(Treatment, SeasonX) %>%
  summarise(mean(Shannon),std.err(Shannon))
colnames(shan_season) = c("Treatment","Season","Shannon","SE.shan")

p_seasshan = ggplot(shan_season, aes(Season, Shannon, fill = Treatment)) + geom_bar(position = position_dodge(), stat="identity", colour = 'black') + geom_errorbar(aes(ymax = Shannon+SE.shan, ymin = Shannon-SE.shan), width=0.25, position = position_dodge(.9)) + labs(x = "", y = "Shannon's diversity index") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 10), strip.text = element_text(size = 10), axis.text.x = element_text(size=8, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) + ylim(0,1) + scale_fill_grey() + theme(legend.title=element_blank()) + scale_y_continuous(expand = c(0,0)) + labs(title = "") + scale_x_discrete(labels = c("Su16", "Fa16", "Wi17", "Sp17", "Su17"))


simp_season = new_df %>%
  group_by(Treatment, SeasonX) %>%
  summarise(mean(Simpson), std.err(Simpson))
colnames(simp_season) = c("Treatment", "Season", "Simpson", "SE.simp")

p_seassimp = ggplot(simp_season, aes(Season, Simpson, fill = Treatment)) + geom_bar(position = position_dodge(), stat="identity", colour = 'black') + geom_errorbar(aes(ymax = Simpson + SE.simp, ymin = Simpson - SE.simp), width = 0.25, position = position_dodge(.9)) + labs(x = "", y = "Simpson's diversity index") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 10), strip.text = element_text(size = 10, face = "bold"), axis.text.x = element_text(size=8, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) + ylim(0,0.6) + scale_fill_grey() + theme(legend.title=element_blank()) + scale_y_continuous(expand = c(0,0)) + labs(title = "") + scale_x_discrete(labels = c("Su16", "Fa16", "Wi17", "Sp17", "Su17"))

rich_season = new_df %>%
  group_by(Treatment, SeasonX) %>%
  summarise(mean(Richness), std.err(Richness))
colnames(rich_season) = c("Treatment", "Season", "Richness", "SE.rich")

p_seasrich = ggplot(rich_season, aes(Season, Richness, fill = Treatment)) + geom_bar(position = position_dodge(), stat="identity", colour = 'black') + geom_errorbar(aes(ymax = Richness + SE.rich, ymin = Richness - SE.rich), width = 0.25, position = position_dodge(.9)) + labs(x = "", y = "Species richness") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 10), strip.text = element_text(size = 15), axis.text.x = element_text(size=8, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) + ylim(0,4) + scale_fill_grey() + theme(legend.title=element_blank()) + scale_y_continuous(expand = c(0,0)) + labs(title = "") + scale_x_discrete(labels = c("Su16", "Fa16", "Wi17", "Sp17", "Su17"))

plot_grid(p_seasabun, p_seasshan, p_seassimp, p_seasrich, labels = "AUTO", label_x = 0.05)

```

##size.freq
```{r, echo=FALSE}
ggplot(data=legare_net, aes(x = Total.Length..mm.)) + geom_histogram(binwidth = 5) + facet_grid(~Species) + theme_bw() + labs(x = "Length (mm)", y = "Frequency")

```

#temp
```{r}
#just some fooling around
plot(Abundance-PalaemonetesPugio ~ Temperature, col = Treatment, pch = 16, data = new_df)
legend("topleft", legend=levels(new_df$Treatment), text.col=seq_along(levels(new_df$Treatment)))

m_reg = with(new_df[new_df$Treatment == "Mussels",], lm(Abundance-PalaemonetesPugio ~ Temperature))
nm_reg = with(new_df[new_df$Treatment == "No_mussels",], lm(Abundance-PalaemonetesPugio ~ Temperature))

abline(m_reg) #These are probably not the best models!
abline(nm_reg, col = 'red')

plot(Abundance-PalaemonetesPugio ~ Treatment, data = new_df[new_df$CharlestonHeight > 1.8,])
```

##Individual species' patterns
```{r}
spp_df = new_df %>%
  filter(Month != "July") %>%
  filter(Month != "July/Aug") %>%
  select(PalaemonetesPugio, FundulusHeteroclitus, CallinectesSapidus, LitopenaeusSetiferus, LeiostomusXanthurus, Month) %>%
  group_by(Month) %>%
  summarise(mean(PalaemonetesPugio), mean(FundulusHeteroclitus), mean(CallinectesSapidus), mean(LitopenaeusSetiferus), mean(LeiostomusXanthurus), std.err(PalaemonetesPugio), std.err(FundulusHeteroclitus), std.err(CallinectesSapidus), std.err(LitopenaeusSetiferus), std.err(LeiostomusXanthurus))
colnames(spp_df) = c("Month", "Pp", "Fh", "Cs", "Ls", "Lx", "se.pp", "se.fh", "se.cs", "se.ls", "se.lx")

spp_df$Month = factor(spp_df$Month, levels = c("July", "August", "September", "October", "November", "December", "January", "February", "March", "April", "May", "June")) #Ordering the months

#Palaemonetes pugio
ggplot(spp_df, aes(Month, Pp, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymax = Pp + se.pp, ymin = Pp - se.pp), width=0.25) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, face = "bold"), strip.text = element_text(size = 15, face = "bold"), axis.text.x = element_text(size=11), axis.text.y = element_text(size = 15)) + ylim(0,25) + labs(y =  expression(italic(Palaemonetes~pugio)~abundance))

#Fundulus heteroclitus
ggplot(spp_df, aes(Month, Fh, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymax = Fh + se.fh, ymin = Fh - se.fh), width=0.25)  + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, face = "bold"), strip.text = element_text(size = 15, face = "bold"), axis.text.x = element_text(size=11), axis.text.y = element_text(size = 15)) + scale_y_continuous(breaks = seq(0,10,2)) + labs(y =  expression(italic(Fundulus~heteroclitus)~abundance))

#Callinectes sapidus
ggplot(spp_df, aes(Month, Cs, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymax = Cs + se.cs, ymin = Cs - se.cs), width=0.25) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, face = "bold"), strip.text = element_text(size = 15, face = "bold"), axis.text.x = element_text(size=11), axis.text.y = element_text(size = 15)) + scale_y_continuous(breaks = seq(0,2.5,1)) + labs(y =  expression(italic(Callinectes~sapidus)~abundance))


#Litopenaeus setiferus
ggplot(spp_df, aes(Month, Ls, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymax = Ls + se.ls, ymin = Ls - se.ls), width=0.25) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, face = "bold"), strip.text = element_text(size = 15, face = "bold"), axis.text.x = element_text(size=11), axis.text.y = element_text(size = 15)) + ylim(0,7) + labs(y =  expression(italic(Litopenaeus~setiferus)~abundance))


#Leiostomus xanthurus
ggplot(spp_df, aes(Month, Lx, group = 1)) + geom_point() + geom_line() + geom_errorbar(aes(ymax = Lx + se.lx, ymin = Lx - se.lx), width=0.25) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, face = "bold"), strip.text = element_text(size = 15, face = "bold"), axis.text.x = element_text(size=11), axis.text.y = element_text(size = 15)) + scale_y_continuous(breaks = seq(0,1.5,1)) + labs(y =  expression(italic(Leiostomus~xanthurus)~abundance))


#C. sapidus size
csap_df = legare_net %>%
  filter(Species == "Callinectes sapidus")
csap_df$Month = c(rep("Jul. 2016", 4), rep("Aug. 2016", 17), rep("Sep.", 28), rep("Oct.", 15), rep("Nov.", 14), rep("Dec.", 6), rep("Jan.", 1), rep("Feb.", 4), rep("Mar.", 6), rep("Apr.", 4), rep("May", 3), rep("Jun.", 1), rep("Jul. 2017", 1), rep("Aug. 2017", 1))
csap_df$Month = factor(csap_df$Month, levels = c("Jul. 2016", "Aug. 2016", "Sep.", "Oct.", "Nov.", "Dec.", "Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul. 2017", "Aug. 2017"))
csap_df$Season = c(rep("Fall 2016", 64), rep("Winter 2017", 33), rep("Spring 2017", 8))
csap_df$SeasonX = c(rep("Su16", 21), rep("Fa16", 57), rep("Wi17", 11), rep("Sp17", 13), rep("Su17", 3))
csap_df$Season = factor(csap_df$Season, levels = c("Fall 2016", "Winter 2017", "Spring 2017"))
csap_df$SeasonX = factor(csap_df$Season, levels = c("Su16", "Fa16", "Wi17",  "Sp17", "Su17"))

ggplot(data = csap_df, aes(Total.Length..mm.)) + geom_histogram(binwidth = 10, fill = "black") + labs(x = "Carapace width (mm)", y = "Number collected") + facet_grid(~SeasonX) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, colour = "black"), strip.text = element_text(size = 15, colour = "black"), axis.text.x = element_text(size=15, colour = "black"), axis.text.y = element_text(size = 15, colour = "black")) + scale_y_continuous(expand = c(0,0))
#unequal sample sizes geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]), binwidth = 5)
```

##Physical conditions
```{r}
phys_frame = new_df %>%
  select(Date, Month, Temperature, Salinity, CharlestonHeight, Season)
phys_frame = unique(phys_frame)
phys_frame$Order = as.factor(seq(1:28))
tapply(new_df$Abundance, new_df$Date, sum)
phys_frame$Abun = c(43, 66, 21, 48, 60, 15, 12, 93, 36, 67, 100, 112, 17, 37, 18, 8, 1, 3, 25, 7, 54, 45, 15, 20, 146, 116, 34, 28)

ggplot(phys_frame, aes(Order, Temperature)) + geom_point() + scale_x_discrete(breaks = c(6,17,26), labels=c("July - October 2016","November 2016 - April 2017","April - August 2017")) + xlab("") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=10, colour = "black"), axis.text.y = element_text(size = 15, colour = "black"), axis.ticks.x = element_blank(), legend.position = "none") +ylab("Temperature (°C)") + geom_rect(aes(xmin = 0.75, xmax = 11.25, ymin = 0, ymax = Inf), alpha = 0.005) + geom_rect(aes(xmin = 22.75, xmax = 28.25, ymin = 0, ymax = Inf), alpha = 0.005) + scale_y_continuous(expand = c(0,0.25)) + geom_text(aes(x = 5, y = 2, label = "Fall 2016")) + geom_text(aes(x = 17, y = 2, label = "Winter 2017")) + geom_text(aes(x = 25.5, y = 2, label = "Spring 2017"))

#Julian days
phys_frame$standarddate = c('2016-07-21', '2016-08-04', '2016-08-09', '2016-08-24', '2016-08-25','2016-09-07','2016-09-08','2016-09-21','2016-09-22','2016-10-03','2016-10-21','2016-11-02','2016-11-18','2016-12-02','2016-12-16','2017-01-16','2017-01-31','2017-02-13','2017-02-28','2017-03-13','2017-03-31','2017-04-11','2017-04-28','2017-05-12','2017-05-22','2017-06-28','2017-07-17','2017-08-11')
phys_frame$DateX = as.Date(c('2016-07-21', '2016-08-04', '2016-08-09', '2016-08-24', '2016-08-25','2016-09-07','2016-09-08','2016-09-21','2016-09-22','2016-10-03','2016-10-21','2016-11-02','2016-11-18','2016-12-02','2016-12-16','2017-01-16','2017-01-31','2017-02-13','2017-02-28','2017-03-13','2017-03-31','2017-04-11','2017-04-28','2017-05-12','2017-05-22','2017-06-28','2017-07-17','2017-08-11'))
library(lubridate)
yyy = as.Date(phys_frame$standarddate)
phys_frame$Julian = yday(yyy)
with(phys_frame, plot(Temperature ~ Julian))
with(phys_frame, plot(Abun ~ Julian))

ggplot(phys_frame, aes(DateX, Temperature)) + geom_point() + xlab("") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=12, colour = "black"), axis.text.y = element_text(size = 15, colour = "black")) + ylab("Temperature (°C)") +   scale_y_continuous(limits = c(0, 40), expand = c(0, 0))
```

##end
