---
title: "Mac_ashelevation"
author: "Asa Julien"
date: "8/13/2017"
output: html_document
---
##Ashley grid I
```{r pressure, echo=FALSE}
library(lattice)
library(ggplot2)
library(rms)
library(pscl)
library(pROC)
library(rgl)

ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

#All together
ashglm = glm(Mussel.presence ~ Elevation * Block, family = binomial, data = ashgrid)
summary(ashglm)

full_mod = ashglm
main_mod = update(full_mod, . ~ . - Elevation:Block)
elev_mod = update(main_mod, . ~ . - Block)
elev_mod2 = update(elev_mod, . ~ . + I(Elevation^2))
elev_mod3 = update(elev_mod2, . ~ . + I(Elevation^3))
elev_mod4 = update(elev_mod2, . ~ . + Block)
elev_mod5 = update(elev_mod2, . ~ . + Block + Elevation:Block)

anova(full_mod, main_mod, elev_mod, test='LRT')
AIC(full_mod, main_mod, elev_mod)

anova(elev_mod, elev_mod2, elev_mod4, elev_mod5, test='LRT')
AIC(elev_mod, elev_mod2, elev_mod4, elev_mod5) #model 4 is the best

#add salinity back in - plot both
summary(elev_mod4)

#model fits; pseudo r^2
full_r2 = pR2(full_mod)
main_r2 = pR2(main_mod)
mod_r2 = pR2(elev_mod)
mod2_r2 = pR2(elev_mod2)
mod4_r2 = pR2(elev_mod4)
mod5_r2 = pR2(elev_mod5)

#plotting data and values predicted by models
new_data = data.frame(Elevation = seq(0, 1, length.out = 50), Block = rep(c("20-25"), each = 50))
new_data2 = data.frame(Elevation = seq(0, 1, length.out = 50), Block = rep(c("15-20"), each = 50))
new_data3 = data.frame(Elevation = seq(0, 1, length.out = 50), Block = rep(c("10-15"), each = 50))
new_data4 = data.frame(Elevation = seq(0, 1, length.out = 50), Block = rep(c("5-10"), each = 50))

plot(Mussel.presence ~ Elevation, data=ashgrid, pch = 20, col = ashgrid$Block, xlab = "Elevation (m)", ylab = "Probability of Geukensia demissa occurrence")
legend(-0.1, 1, unique(ashgrid$Block), col = c("green", "red", "black", "blue"), pch = 20)
text(-0.02, 0.78, "Salinity (ppt)")

lines(new_data$Elevation, predict(elev_mod4, newdata=new_data, type='response'),
      col='green')
lines(new_data2$Elevation, predict(elev_mod4, newdata=new_data2, type='response'),
      col='red')
lines(new_data3$Elevation, predict(elev_mod4, newdata=new_data3, type='response'),
      col='black')
lines(new_data4$Elevation, predict(elev_mod4, newdata=new_data4, type='response'),
      col='blue')

lines(new_data$Elevation, predict(elev_mod, newdata=new_data, type='response'),
      col='purple')
lines(new_data$Elevation, predict(elev_mod2, newdata=new_data, type='response'),
      col='pink')

```


##Elevation above MHW
```{r pressure, echo=FALSE}
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

#All together - something weird goes on when above chunk is executed, but the code below will work
ashglm_mhw = glm(Mussel.presence ~ MHW * Block, family = binomial, data = ashgrid)
summary(ashglm_mhw)

full_mhw = ashglm_mhw
main_mhw = update(full_mhw, . ~ . - MHW:Block)
elev_mhw = update(main_mhw, . ~ . - Block)
elev_mhw2 = update(elev_mhw, . ~ . + I(MHW^2))
elev_mhw3 = update(elev_mhw2, . ~ . + I(MHW^3))
elev_mhw4 = update(elev_mhw2, . ~ . + Block)
elev_mhw5 = update(elev_mhw2, . ~ . + Block + MHW:Block)

anova(full_mhw, main_mhw, elev_mhw, test='LRT')
AIC(full_mhw, main_mhw, elev_mhw)

anova(elev_mhw, elev_mhw2, elev_mhw4, elev_mhw5, test='LRT')
AIC(elev_mhw, elev_mhw2, elev_mhw4, elev_mhw5) #model 4 is the best

#add salinity back in - plot both
summary(elev_mhw4)

#model fits; pseudo r^2
pR2(full_mhw)
pR2(main_mhw)
pR2(elev_mhw)
pR2(elev_mhw2)
pR2(elev_mhw4)
pR2(elev_mhw5)

#plotting data and values predicted by models
MHW_data = data.frame(MHW = seq(-1.2, .2, length.out = 50), Block = rep(c("20-25"), each = 50))
MHW_data2 = data.frame(MHW = seq(-1.2, .2, length.out = 50), Block = rep(c("15-20"), each = 50))
MHW_data3 = data.frame(MHW = seq(-1.2, .2, length.out = 50), Block = rep(c("10-15"), each = 50))
MHW_data4 = data.frame(MHW = seq(-1.2, .2, length.out = 50), Block = rep(c("5-10"), each = 50))

plot(Mussel.presence ~ MHW, data=ashgrid, pch = 20, col = ashgrid$Block, xlab = "Elevation above MHW (m)", ylab = "Probability of Geukensia demissa occurrence")
legend(-1.1, 1, unique(ashgrid$Block), col = c("green", "red", "black", "blue"), pch = 20)
text(-1.03, 0.78, "Salinity (ppt)")

lines(MHW_data$MHW, predict(elev_mhw4, newdata=MHW_data, type='response'),
      col='green')
lines(MHW_data2$MHW, predict(elev_mhw4, newdata=MHW_data2, type='response'),
      col='red')
lines(MHW_data3$MHW, predict(elev_mhw4, newdata=MHW_data3, type='response'),
      col='black')
lines(MHW_data4$MHW, predict(elev_mhw4, newdata=MHW_data4, type='response'),
      col='blue')

lines(MHW_data$MHW, predict(elev_mhw, newdata=new_data, type='response'),
      col='purple')
lines(MHW_data$MHW, predict(elev_mhw2, newdata=new_data, type='response'),
      col='pink')

```

##Goodness of fit/model diagnostics
```{r}
#sensitivity and specificity, ROC curves. There are 108 presences (I THINK) and 132 absences. Calculating these at different 'cutoffs'

fit_mhw = elev_mhw4$fitted.values
fit_mhw2 = elev_mhw4$fitted.values[ashgrid$Block == "20-25"] #1-60
fit_mhw3 = elev_mhw4$fitted.values[ashgrid$Block == "15-20"] #61-120
fit_mhw4 = elev_mhw4$fitted.values[ashgrid$Block == "10-15"] #121-180
fit_mhw5 = elev_mhw4$fitted.values[ashgrid$Block == "5-10"] #181-240

#Using the R package pROC
summary(elev_mhw4)
prob = predict(elev_mhw4, type = c("response")) #same as fit_mhw!

ashgrid$prob = fit_mhw

ashgrid$prob2 = fit_mhw2 #EACH OF THESE should ONLY be 60, BUT THEY REPEAT IN REGULAR DATA FRAME!
ashgrid$prob3 = fit_mhw3
ashgrid$prob4 = fit_mhw4
ashgrid$prob5 = fit_mhw5

g = roc(Mussel.presence ~ prob, data = ashgrid)
g2 = roc(Mussel.presence[1:60] ~ prob2[1:60], data = ashgrid)
g3 = roc(Mussel.presence[61:120] ~ prob3[61:120], data = ashgrid)
g4 = roc(Mussel.presence[121:180] ~ prob4[121:180], data = ashgrid)
g5 = roc(Mussel.presence[181:240] ~ prob5[181:240], data = ashgrid)

plot(g)
plot(g2)
plot(g3)
plot(g4)
plot(g5)

auc(g) #86.2%! Corroborated; see below.
# "Although it is not obvious from its definition, the area under the ROC curve (AUC) has a somewhat appealing interpretation. It turns out that the AUC is the probability that if you were to take a random pair of observations, one with Y=1 and one with Y=0, the observation with Y=1 has a higher predicted probability than the other. The AUC thus gives the probability that the model correctly ranks such pairs of observations."
auc(g2)
auc(g3)
auc(g4)
auc(g5) #Not as good a fit for the most and least saline blocks, but not bad for the middle two. Not sure what to do about this discrepancy.

#AUC (area under ROC)
fit_pos = fit_mhw[ashgrid$Mussel.presence==1]
fit_neg = fit_mhw[ashgrid$Mussel.presence==0]
wilcox.test(x = fit_pos, y = fit_neg)
12290/(108*132)
#AUC = 86.2%
```


##Elevation in relation to tidal position
```{r pressure, echo=FALSE}
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

#All together - something weird goes on when above chunk is executed, but the code below will work
ashglm_position = glm(Mussel.presence ~ Position * Block, family = binomial, data = ashgrid)
summary(ashglm_position)

full_position = ashglm_position
main_position = update(full_position, . ~ . - Position:Block)
elev_position = update(main_position, . ~ . - Block)
elev_position2 = update(elev_position, . ~ . + I(Position^2))
elev_position3 = update(elev_position2, . ~ . + I(Position^3))
elev_position4 = update(elev_position2, . ~ . + Block)
elev_position5 = update(elev_position2, . ~ . + Block + Position:Block)

anova(full_position, main_position, elev_position, test='LRT')
AIC(full_position, main_position, elev_position)

anova(elev_position, elev_position2, elev_position4, elev_position5, test='LRT')
AIC(elev_position, elev_position2, elev_position4, elev_position5) #model 4 is the best

#add salinity back in - plot both
summary(elev_position4)

#model fits; pseudo r^2
pR2(full_position)
pR2(main_position)
pR2(elev_position)
pR2(elev_position2)
pR2(elev_position4)
pR2(elev_position5)

#plotting data and values predicted by models
position_data = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("20-25"), each = 50))
position_data2 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("15-20"), each = 50))
position_data3 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("10-15"), each = 50))
position_data4 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("5-10"), each = 50))

plot(Mussel.presence ~ Position, data=ashgrid, pch = 20, col = ashgrid$Block, xlab = "Tidal position (%)", ylab = "Probability of Geukensia demissa occurrence")
legend(.4, 1, unique(ashgrid$Block), col = c("green", "red", "black", "blue"), pch = 20)
text(0.44, 0.78, "Salinity (ppt)")

lines(position_data$Position, predict(elev_position4, newdata=position_data, type='response'),
      col='green')
lines(position_data2$Position, predict(elev_position4, newdata=position_data2, type='response'),
      col='red')
lines(position_data3$Position, predict(elev_position4, newdata=position_data3, type='response'),
      col='black')
lines(position_data4$Position, predict(elev_position4, newdata=position_data4, type='response'),
      col='blue')


```


##Salinity as a continuous variable
```{r pressure, echo=FALSE}
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

site_sal = rev(c(8.35149, 10.96029, 13.86604, 14.23241, 16.46788, 18.12259, 22.67457, 23.05144)) #YOU SHOULD DOUBLE CHECK THESE AND MAKE SURE THEY ARE CALCULATED WELL

ashgrid$salinity = rep(site_sal, each = 30) #salinity at each site is now continuous, based on interpolation from Kelsey's data

#models
ashglm_x = glm(Mussel.presence ~ MHW + salinity, family = binomial, data = ashgrid)
summary(ashglm_x)

full_x = ashglm_x
elev_x = update(full_x, . ~ . - salinity)
elev_x2 = update(elev_x, . ~ . + I(MHW^2))
elev_x3 = update(elev_x2, . ~ . + I(MHW^3))
elev_x4 = update(elev_x2, . ~ . + salinity)
elev_x5 = update(elev_x4, . ~ . + I(salinity^2))
elev_x6 = update(elev_x5, . ~ . - salinity)
elev_x7 = update(elev_x5, . ~ . - MHW)

anova(full_x, elev_x, test='LRT')
AIC(full_x, elev_x)

anova(full_x, elev_x2, elev_x4, elev_x5, elev_x6, elev_x7, test='LRT')
AIC(full_x, elev_x2, elev_x3, elev_x4, elev_x5, elev_x6, elev_x7) #model 5 is the best

summary(elev_x5) #has a lower and upper salinity tolerance - just like elevation - which might be why the quadratic equation works better

#model fits; pseudo r^2
pR2(full_x)
pR2(elev_x)
pR2(elev_x2)
pR2(elev_x4)
pR2(elev_x5)
pR2(elev_x6)

#plotting data and values predicted by models

n_sal_bins = 10
min_sal = min(ashgrid$salinity)
max_sal = max(ashgrid$salinity)
x_data = data.frame(MHW = seq(-1.2, 0.2, length.out = 50),
                    salinity = rep(seq(min_sal, max_sal,
                                       length.out=n_sal_bins), each = 50))

sal_bins = seq(min_sal, max_sal, length.out = n_sal_bins)
int_col_index = as.numeric(cut(x_data$salinity, sal_bins,
                           include.lowest = T))
obs_col_index = as.numeric(cut(ashgrid$salinity, sal_bins, include.lowest = T))
col_ramp = colorRampPalette(c('blue', 'red'))(length(sal_bins)) 
int_cols = col_ramp[int_col_index]
obs_cols = col_ramp[obs_col_index]

par(mfrow=c(1, 1))
plot(jitter(Mussel.presence, .1) ~ MHW, data=ashgrid, pch = 20,
     col = obs_cols, xlab = "Elevation above MHW (m)", 
     ylab = "Probability of Geukensia demissa occurrence")
#lines(x_data$MHW, predict(elev_x5, newdata=x_data, type='response'),
#      col= int_cols)
for(i in seq_along(sal_bins)) {
    lines(x_data$MHW[int_col_index == i], 
          predict(elev_x5, newdata=x_data[int_col_index == i, ],
                  type='response'), col=col_ramp[i])
}
plot(jitter(Mussel.presence, .1) ~ salinity, data=ashgrid, pch = 20,
     col = obs_cols, xlab = "Salinity", 
     ylab = "Probability of Geukensia demissa occurrence")
#lines(x_data$MHW, predict(elev_x5, newdata=x_data, type='response'),
#      col= int_cols)
for(i in seq_along(sal_bins)) {
    lines(x_data$salinity[int_col_index == i], 
          predict(elev_x5, newdata=x_data[int_col_index == i, ],
                  type='response'), col=col_ramp[i])
}

scatterplot3d(ashgrid$MHW, ashgrid$salinity, ashgrid$Mussel.presence)


x_data$response =  predict(elev_x5, newdata=x_data, type='response')

which(x_data == max(x_data$response), arr.ind=TRUE)
x_data[987,]

#ROC curve
fit_x = elev_x5$fitted.values
g_x = roc(Mussel.presence ~ fit_x, data = ashgrid)
plot(g_x)
auc(g_x) #0.87, not too shabby

```


d
