---
title: "Folly Ace comp"
author: "Asa Julien"
date: "3/14/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(dplyr)
library(FSA)
library(nlstools)
library(lattice)
library(ggplot2)
library(lmtest)
#windows:
site_compare = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Site comparison\\CSV files\\Comparison.csv")
fbcp_freq = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Size frequency\\CSV files\\sizeagefreq_fbcp.csv")
#mac:
site_compare = read.csv("~/Documents/Ribbed mussel/Data/Site comparison/CSV files/Comparison.csv")
fbcp_freq = read.csv("~/Documents/Ribbed mussel/Data/Size frequency/CSV files/sizeagefreq_fbcp.csv")

temp_site = site_compare[,c(3,5,6)]
temp_folly = fbcp_freq[,c(1,6,7)]

all_sites = rbind(temp_site, temp_folly)

un_folly = rbind(temp_site[temp_site$Location == "St. Pierre Creek",], temp_folly)

h_folly = rbind(temp_site[temp_site$Location == "Fish Creek",], temp_folly)
```

#comparisons of length, age, density
```{r}
kruskal.test(Length.mm ~ Location, data = all_sites)
dunnTest(Length.mm ~ Location, data = all_sites)

kruskal.test(Growth.bands ~ Location, data = all_sites)
dunnTest(Growth.bands ~ Location, data = all_sites)

wilcox.test(Length.mm ~ Location, data = un_folly)
wilcox.test(Growth.bands ~ Location, data = un_folly)

#Density
all_den = rbind(den.fbcp[,c(6,7,5)], den_compare[,c(1,3,4)])
unfoll_den = all_den[all_den$Status != "Harvested",]
allden_aov = aov (sqrt(Density) ~ Status, data = all_den) #note square root transformation
unfoll_aovden = aov(sqrt(Density)~Status, data = unfoll_den)
summary(allden_aov)
TukeyHSD(allden_aov) #Both harvested and unharvested sites were significantly greater in density than the Folly site, not from each other though

#fc-spc
site_compare$Location = factor(site_compare$Location, levels=c("Fish Creek", "St. Pierre Creek"), labels=c("Fish Creek (harvested)", "St. Pierre Creek (unharvested)"))

ggplot(na.omit(site_compare), aes(x = Growth.bands, y = Length.mm, group = Location)) + geom_point(aes(colour = Location)) + geom_smooth(method = "nls", formula = y ~ Linf * (1 - exp(-K * (x - t0))), method.args = list(start=c(Linf = 108.54, K = 0.29, t0 = -0.65)), se=F, aes(col = Location)) + scale_y_continuous(name = "Length (mm)", limits = c(0, 120)) + xlab("Age (growth bands)")

#spc-fb
un_folly$Location = factor(un_folly$Location, levels=c("St. Pierre Creek", "Folly Beach County Park (side B)"), labels=c("St. Pierre Creek (unharvested)", "Folly Beach"))

ggplot(na.omit(un_folly), aes(x = Growth.bands, y = Length.mm, group = Location)) + geom_point(aes(colour = Location)) + geom_smooth(method = "nls", formula = y ~ Linf * (1 - exp(-K * (x - t0))), method.args = list(start=c(Linf = 108.54, K = 0.29, t0 = -0.65)), se=F, aes(col = Location)) + scale_y_continuous(name = "Length (mm)", limits = c(0, 120)) + xlab("Age (growth bands)")

#all
all_sites$Location = factor(all_sites$Location, levels=c("Fish Creek", "St. Pierre Creek", "Folly Beach County Park (side B)"), labels=c("FC", "SPC", "FBCP"))

ggplot(na.omit(all_sites), aes(x = Growth.bands, y = Length.mm, group = Location)) + geom_point(aes(colour = Location, shape = Location), alpha = 0.6) + geom_smooth(method = "nls", lwd = 0.75, formula = y ~ Linf * (1 - exp(-K * (x - t0))), method.args = list(start=c(Linf = 108.54, K = 0.29, t0 = -0.65)), se=F, aes(col = Location)) + scale_y_continuous(name = expression(italic(Geukensia~demissa)~shell~height~(mm)), limits = c(0, 120), expand = c(0,0)) + scale_x_continuous(limits = c(-0.5,20), expand = c(0,0)) + xlab("Age (number of shell growth bands)") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15, colour = "black"), strip.text = element_text(size=15, colour = "black"), axis.text.x = element_text(size=13, colour = "black"), axis.text.y = element_text(size = 13, colour = "black")) + theme(legend.text = element_text(size=8)) + scale_colour_grey() + geom_hline(yintercept = 76.2, lty = "dashed")

```

#Unharvested - Folly
```{r}
#careful of overlap in object names
vbLKt = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbLK = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbLt = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0[Location])))
vbKt = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbL = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0)))
vbK = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbt = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0[Location])))
vb0 = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0)))

#starting values. They are fairly similar so I'm going to use the same for each group (pooled).
sv0 = vbStarts(Length.mm ~ Growth.bands, data = un_folly)
svLKt = list(Linf = c(103.2192,103.2192), K = c(0.356,0.356), t0 = c(-0.4745,-0.4745))

library(minpack.lm)
curve_x = nlsLM(Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0))), start = sv0, data = un_folly)
coef(curve_x) #103.22, 0.36, -0.47


#fit model
fitLKt = nls(vbLKt, data = un_folly, start = svLKt)
residPlot(fitLKt, col = rgb(0, 0, 0, 1/3))

fit0 = nls(vb0, data = un_folly, start = list(Linf = 103.2192, K = 0.356, t0 = -0.4745))
residPlot(fit0)

lrt(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ") #Differences!
extraSS(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ")

#differences in nested models
svLK = Map(rep, sv0, c(2,2,1))
svLt = Map(rep, sv0, c(2,1,2))
svKt = Map(rep, sv0, c(1,2,2))

fitLK = nls(vbLK, data = un_folly, start = svLK)
fitLt = nls(vbLt, data = un_folly, start = svLt)
fitKt = nls(vbKt, data = un_folly, start = svKt)

lrt(fitLK,fitLt,fitKt,com=fitLKt,com.name="All param diff",
sim.names=c("Linf,K diff","Linf,t0 diff","K,t0 diff"))

#next subsets compared to fitLK, highest loglikelihood
svL = Map(rep, sv0, c(2,1,1))
svK = Map(rep, sv0, c(1,2,1))
fitL = nls(vbL, data = un_folly, start = svL)
fitK = nls(vbK, data = un_folly, start = svK)

lrt(fitL,fitK,com=fitLK,com.name="Linf,K dif",
sim.names=c("Linf dif","K dif")) #Linf differs but K does not

lrt(fitL,fitK,com=fitLKt,com.name="Linf,K,t dif",
sim.names=c("Linf dif","K dif")) #JUST Linf DIFFERS

#final check:
lrt(fit0, com = fitL,com.name = "Linf dif", sim.names = "No param dif")

#all together now
svt = Map(rep, sv0, c(1,1,2))
fitt = nls(vbt, data = un_folly, start = svt)

cbind(AIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0),
BIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0)) #Just different L inf seems to be the best model I think
```

#Harvested - Folly
```{r}
#careful of overlap in object names
vbLKt = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbLK = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbLt = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0[Location])))
vbKt = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbL = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0)))
vbK = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbt = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0[Location])))
vb0 = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0)))

#starting values. They are fairly similar so I'm going to use the same for each group (pooled).
sv0 = vbStarts(Length.mm ~ Growth.bands, data = h_folly)
svLKt = list(Linf = c(105.52,105.52), K = c(0.35,0.35), t0 = c(-0.49,-0.49))


#fit model
library(minpack.lm)
curve_x = nlsLM(Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0))), start = sv0, data = h_folly)
coef(curve_x) #105.52, 0.35, -0.49

fitLKt = nls(vbLKt, data = h_folly, start = svLKt)
residPlot(fitLKt, col = rgb(0, 0, 0, 1/3))

fit0 = nls(vb0, data = h_folly, start = list(Linf = 105.52, K = 0.35, t0 = -0.49))
residPlot(fit0)

lrt(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ") #Differences!
extraSS(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ")

#differences in nested models
svLK = Map(rep, sv0, c(2,2,1))
svLt = Map(rep, sv0, c(2,1,2))
svKt = Map(rep, sv0, c(1,2,2))

fitLK = nls(vbLK, data = site_compare, start = svLK)
fitLt = nls(vbLt, data = site_compare, start = svLt)
fitKt = nls(vbKt, data = site_compare, start = svKt)

lrt(fitLK,fitLt,fitKt,com=fitLKt,com.name="All param diff",
sim.names=c("Linf,K diff","Linf,t0 diff","K,t0 diff"))

#next subsets compared to fitLK, highest loglikelihood
svL = Map(rep, sv0, c(2,1,1))
svK = Map(rep, sv0, c(1,2,1))
fitL = nls(vbL, data = site_compare, start = svL)
fitK = nls(vbK, data = site_compare, start = svK)

lrt(fitL,fitK,com=fitLK,com.name="Linf,K dif",
sim.names=c("Linf dif","K dif")) #Linf differs but K does not

lrt(fitL,fitK,com=fitLKt,com.name="Linf,K,t dif",
sim.names=c("Linf dif","K dif")) #JUST Linf DIFFERS

#final check:
lrt(fit0, com = fitL,com.name = "Linf dif", sim.names = "No param dif")

#all together now
svt = Map(rep, sv0, c(1,1,2))
fitt = nls(vbt, data = site_compare, start = svt)

cbind(AIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0),
BIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0)) #Just different L inf seems to be the best model I think
```


```{r}

```

