---
title: "Untitled"
author: "Asa Julien"
date: "July 21, 2017"
output: html_document
---

##Inundation period
```{r}
library(ggplot2)
library(dplyr)
library(lme4)
library(nlme)

#windows:
hobo = read.csv("C:\\Users\\juliena\\Desktop\\Data\\HOBO data\\CSV files\\hobo.csv", as.is = T)
#mac: 
hobo = read.csv("~/Documents/Ribbed mussel/Data/HOBO/CSV files/hobo.csv", as.is = T)

#convert Period to numeric
hobo$Time = sapply(strsplit(hobo$Period,":"),
  function(x) {
    x <- as.numeric(x)
    x[1]+x[2]/60
    }
)

#Salinity to as factor:
hobo$Salinity = as.factor(hobo$Salinity)

#NOTE: MHW refers to the elevation of the particular position, not the tidal height!

#standard error
std.err = function(x)
  sd(x)/sqrt(length(x))

hobo_lm = lm(Time ~ MHW + CharlestonHeight, data = hobo) #HOBO_ID/SITE???
summary(hobo_lm)
par(mfrow=c(1,2))
termplot(hobo_lm, partial.resid = T, se = T)
plot(hobo$CharlestonHeight, residuals(lm(Time ~ MHW, data=hobo)))

#From NOAA: MHW is 1.65 m above MLLW datum

hobo_mix = lmer(Time ~ MHW + CharlestonHeight + (1|HOBO_ID) + (1|Salinity), data = hobo)
summary(hobo_mix)
plot(hobo_mix)
qqnorm(resid(hobo_mix))
qqline(resid(hobo_mix))

#I have no idea if this is a good idea:
hobo_squared = lmer(I(Time)^2 ~ MHW + CharlestonHeight + (1|HOBO_ID) + (1|Salinity), data = hobo)
summary(hobo_squared)
plot(hobo_squared)
qqnorm(resid(hobo_squared))
qqline(resid(hobo_squared))

hobo_mix2 = lme(Time ~ MHW + CharlestonHeight, data = hobo, random = ~ 1 | Salinity/HOBO_ID)
summary(hobo_mix2) #same exact model

hobo$HOBO_ID = factor(hobo$HOBO_ID, levels = c("hobo_1","hobo_2","hobo_3","hobo_4","hobo_5","hobo_6","hobo_7","hobo_8","hobo_9","hobo_10","hobo_11","hobo_12"))

#plots
p0 = ggplot(hobo, aes(CharlestonHeight, Time))
p0 + geom_point(aes(colour = MHW)) + geom_smooth(method = 'lm', formula = y ~ x)
#p0 + geom_point(aes(colour = MHW)) + geom_smooth(method = 'lm', formula = y ~ x) + labs(x = "Tidal height (m)", y = "Time (h)") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+theme(axis.title = element_text(size = 15), strip.text = element_text(size=15), axis.text.x = element_text(size=13), axis.text.y = element_text(size = 13)) + ylim(0,7) + scale_colour_continuous(name = "Elevation (m)")

p1 = ggplot(hobo, aes(MHW, Time))
p1 + geom_point(aes(colour = CharlestonHeight)) + geom_smooth(method = 'lm', formula = y ~ x)
#p1 + geom_point(aes(fill = CharlestonHeight), colour = 'black', pch = 21) + geom_smooth(method = 'lm', formula = y ~ x, se = F, colour = "black") + labs(x = "Site elevation (from MHW, m)", y = "Inundation period (h)") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size=15), axis.text.x = element_text(size=13, colour = 'black'), axis.text.y = element_text(size = 13, colour = 'black')) + ylim(0,7) + scale_fill_continuous(low="white", high="black", name = "Tidal height (m)\n")

#average time per hobo
hobo$Salinity = as.numeric(hobo$Salinity)

hobo_mn = hobo %>%
  group_by(HOBO_ID) %>%
  select(HOBO_ID, MHW, Salinity, Time, CharlestonHeight) %>%
  summarise(mean(Time), mean(MHW), std.err(Time), mean(Salinity), mean(CharlestonHeight))
colnames(hobo_mn) = c("HOBO_ID", "Time", "MHW", "se_time", "Salinity", "Tide")
hobo_mn$HOBO_ID = factor(hobo_mn$HOBO_ID, levels = c("hobo_1","hobo_2","hobo_3","hobo_4","hobo_5","hobo_6","hobo_7","hobo_8","hobo_9","hobo_10","hobo_11","hobo_12"))

p4 = ggplot(hobo_mn, aes(MHW, Time))
p4 + geom_point() + geom_smooth(method = 'lm', formula = y ~ x) + geom_errorbar(aes(ymin = Time - se_time, ymax = Time + se_time)) + labs(x = "Elevation from MHW (m)", y = "Time (h)")

mn_lm = lm(Time ~ MHW, data = hobo_mn)
summary(mn_lm)

#average time per day
ht_mn = hobo %>%
  group_by(Day) %>%
  filter(n() >= 3) %>%
  select(Time, CharlestonHeight) %>%
  summarise(mean(Time), std.err(Time), mean(CharlestonHeight))
colnames(ht_mn) = c("Day", "Time", "se_time", "Tide")

p5 = ggplot(ht_mn, aes(Tide, Time))
p5 + geom_point() + geom_smooth(method = 'lm', formula = y ~ x) + geom_errorbar(aes(ymin = Time - se_time, ymax = Time + se_time)) + labs(x = "Tidal height (m)", y = "Time (h)")

ht_lm = lm(Time ~ Tide, data = ht_mn)
summary(ht_lm)

#p5 = ggplot(hobo, aes(MHW, Time, colour = as.factor(Salinity)))
#p5 + geom_smooth(method = 'lm', formula = y ~ x, se=F) + geom_point(aes(colour = as.factor(Salinity))) + labs(x = "Elevation from MHW (m)", y = "Inundation period (h)") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size=15), axis.text.x = element_text(size=13), axis.text.y = element_text(size = 13)) + ylim(0,7) + scale_colour_discrete(name = "Site salinity (‰)\n")
```

##Use mixed effects model to predict average inundation period of observed data
```{r}
#windows:
ashgrid = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Elevation\\CSV files\\Ash_grids.csv")
#mac:
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
#manipulate data:
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

site_sal = rev(c(8.35149, 10.96029, 13.86604, 14.23241, 16.46788, 18.12259, 22.67457, 23.05144)) #YOU SHOULD DOUBLE CHECK THESE AND MAKE SURE THEY ARE CALCULATED WELL

ashgrid$Salinity = rep(site_sal, each = 30) #salinity at each site is now continuous, based on interpolation from Kelsey's data

predict_mix = lmer(Time ~ MHW + CharlestonHeight + (1|Salinity), data = hobo) #HOBO_ID removed... can't really use the mixed effects model to predict? Maybe just use hobo_lm
summary(predict_mix)

elev_frame = ashgrid %>%
  select(Grid.ID, MHW, Mussel.presence, Salinity)

elev_frame$CharlestonHeight = rep(1.65, length.out = 240)


elev_frame$inun_times = predict(predict_mix, newdata = elev_frame, type = 'response', allow.new.levels = TRUE) #or just use hobo_lm
plot(jitter(Mussel.presence, .1) ~ inun_times, data=elev_frame, pch = 20)
mean(elev_frame$inun_times[elev_frame$Mussel.presence == 1])
```

