---
title: "Ashley grid surveys"
author: "Asa Julien"
date: "February 15, 2017"
output: html_document
---
##Ashley grid I
```{r pressure, echo=FALSE}
library(lattice)
library(ggplot2)
library(rms)
library(pscl)
library(pROC)
library(rgl)
```

##Salinity as a continuous variable
```{r pressure, echo=FALSE}
#windows:
ashgrid = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Elevation\\CSV files\\Ash_grids.csv")
#mac:
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
#manipulate data:
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

site_sal = rev(c(8.35149, 10.96029, 13.86604, 14.23241, 16.46788, 18.12259, 22.67457, 23.05144))

ashgrid$salinity = rep(site_sal, each = 30) #salinity at each site is now continuous, based on interpolation from Kelsey's data

#models and model selection
ashglm_x = glm(Mussel.presence ~ MHW + salinity, family = binomial, data = ashgrid)
summary(ashglm_x)

full_x = ashglm_x
elev_x = update(full_x, . ~ . - salinity)
salinity_x = update(full_x, . ~ . - MHW)
salinity_x2 = update(salinity_x, . ~ . + I(salinity^2))
elev_x2 = update(elev_x, . ~ . + I(MHW^2))
elev_x3 = update(elev_x2, . ~ . + I(MHW^3))
elev_x4 = update(elev_x2, . ~ . + salinity)
elev_x5 = update(elev_x4, . ~ . + I(salinity^2))
elev_x6 = update(elev_x5, . ~ . - salinity)
elev_x7 = update(elev_x5, . ~ . - MHW)
#getting rid of issue of separation (but also makes model worse):
elev_x8 = update(elev_x5, .~. - MHW - salinity)
elev_x9 = update(salinity_x2, . ~ . + MHW)
#interaction:
elev_int = update(elev_x5, . ~ . - MHW + MHW * salinity)
#additional combinations
elev_x11 = update(elev_x5, . ~ . - MHW - I(salinity^2))
elev_x12 = update(elev_x5, . ~ . - MHW - salinity - I(salinity^2))
elev_x13 = update(elev_x5, . ~ . - MHW - salinity - I(MHW^2))
elev_x14 = update(elev_x5, . ~ . - I(MHW^2) - salinity)

anova(full_x, elev_x, test='LRT')
anova(full_x, salinity_x, test='LRT')
AIC(full_x, elev_x, salinity_x)

anova(full_x, elev_x2, elev_x4, elev_x5, elev_x6, elev_x7, elev_x8, elev_int, elev_x11, elev_x12, elev_x13, elev_x14, test='LRT')
AIC(full_x, elev_x2, elev_x3, elev_x4, elev_x5, elev_x6, elev_x7, elev_x8, elev_int, elev_x11, elev_x12, elev_x13, elev_x14) #model 5 is the best, no evidence for interaction
anova(elev_x5, elev_int, test = 'LRT') #NO SIG DIFF, go with less complex model (ie no interaction)

summary(elev_x5) #has a lower and upper salinity tolerance - just like elevation - which might be why the quadratic equation works better
summary(elev_x8)

#model fits; pseudo r^2
pR2(full_x)
pR2(elev_x)
pR2(elev_x2)
pR2(elev_x4)
pR2(elev_x5)
pR2(elev_x6)
pR2(elev_x7)
pR2(elev_x8)
pR2(elev_int)
pR2(elev_x9)
pR2(elev_x11)
pR2(elev_x12)
pR2(elev_x13)
pR2(elev_x14)
pR2(salinity_x)
pR2(salinity_x2)

#ROC curve; insert model in fit_x object
fit_x = elev_x5$fitted.values
g_x = roc(Mussel.presence ~ fit_x, data = ashgrid)
plot(g_x)
auc(g_x) #0.87, not too shabby

#plotting data and values predicted by models
n_sal_bins = 10
min_sal = min(ashgrid$salinity)
max_sal = max(ashgrid$salinity)
x_data = data.frame(MHW = seq(-1.2, 0.2, length.out = 50),
                    salinity = rep(seq(min_sal, max_sal,
                                       length.out=n_sal_bins), each = 50))

sal_bins = seq(min_sal, max_sal, length.out = n_sal_bins)
int_col_index = as.numeric(cut(x_data$salinity, sal_bins,
                           include.lowest = T))
obs_col_index = as.numeric(cut(ashgrid$salinity, sal_bins, include.lowest = T))
col_ramp = colorRampPalette(c('blue', 'red'))(length(sal_bins)) 
int_cols = col_ramp[int_col_index]
obs_cols = col_ramp[obs_col_index]

#tiff("Elev.tiff", width = 7, height = 5, units = 'in', res = 300)
#tiff("x1.tiff", width = 4200, height = 3000, units = 'px', res = 750)
#first in inches, second in pixels!
par(mfrow=c(1,1))
par(mar=c(c(5, 4, 4, 0) + 0.1))
layout(matrix(1:2, ncol = 2), widths = c(4,1), heights = c(1,1))
layout.show(n=2)
plot(jitter(Mussel.presence, .1) ~ MHW, data=ashgrid, pch = 20,
     col = obs_cols, xlab = "Elevation from MHW (m)", 
     ylab = expression(Probability~of~italic(Geukensia~demissa)~occurrence))
#lines(x_data$MHW, predict(elev_x5, newdata=x_data, type='response'),
#      col= int_cols)
for(i in seq_along(sal_bins)) {
    lines(x_data$MHW[int_col_index == i], 
          predict(elev_x5, newdata=x_data[int_col_index == i, ],
                  type='response'), col=col_ramp[i], lwd = 1.8)
}

text(x = -0.15, y = c(0.06, 0.18, 0.42, 0.67, 0.77, 0.905), labels = c('8.4‰', '10.0‰', '11.6‰', '13.3‰', '23.0‰', '18.2‰'), cex = 0.8)

par(mar=c(c(5, 1, 4, 2) + 0.1))

#legend
#tiff("Legend.tiff", width = 2, height = 4, units = 'in', res = 300)
legend_image <- as.raster(matrix(int_cols, ncol=1))
legend_image = apply(legend_image, 2, rev) #reverses image!
plot(c(0,1),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Salinity (‰)', font.main = 1, cex.main = 0.95)
text(x=0.1, y = seq(0,1,l=2), labels = seq(8,23,l=2))
rasterImage(legend_image, 0.25, 0, 1, 1)
#dev.off()

par(mar=c(c(5, 4, 4, 2) + 0.1)) #default

#95% confidence intervals; messy
#ci_dat = predict(elev_x5, newdata = x_data, type = 'response', se.fit = T)
#with(ci_dat, lines(x_data$MHW, (fit+1.96*se.fit), lty=2))
#with(ci_dat, lines(x_data$MHW, (fit-1.96*se.fit), lty=2))

#dev.off()

plot3d(ashgrid$MHW, ashgrid$salinity, ashgrid$Mussel.presence)

x_data$response =  predict(elev_x5, newdata=x_data, type='response')

which(x_data == max(x_data$response), arr.ind=TRUE)
x_data[337,]

#just to visualize the relative position
xxx = ashgrid[,c(1,6,15)]
ggplot(xxx, aes(x = Elevation, y = Position)) + geom_point(aes(colour = Grid.ID))
```

##Elevation in relation to tidal position
```{r pressure, echo=FALSE}
#windows:
ashgrid = read.csv(("C:\\Users\\juliena\\Desktop\\Data\\Elevation\\CSV files\\Ash_grids.csv"))
#mac:
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
#manipulate data:
ashgrid$Position = with(ashgrid, MLW/(MLW-MHW))
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

#All together - something weird goes on when above chunk is executed, but the code below will work
ashglm_position = glm(Mussel.presence ~ Position * Block, family = binomial, data = ashgrid)
summary(ashglm_position)

full_position = ashglm_position
main_position = update(full_position, . ~ . - Position:Block)
elev_position = update(main_position, . ~ . - Block)
elev_position2 = update(elev_position, . ~ . + I(Position^2))
elev_position3 = update(elev_position2, . ~ . + I(Position^3))
elev_position4 = update(elev_position2, . ~ . + Block)
elev_position5 = update(elev_position2, . ~ . + Block + Position:Block)

anova(full_position, main_position, elev_position, test='LRT')
AIC(full_position, main_position, elev_position)

anova(elev_position, elev_position2, elev_position4, elev_position5, test='LRT')
AIC(elev_position, elev_position2, elev_position4, elev_position5) #model 4 is the best

#add salinity back in - plot both
summary(elev_position4)

#model fits; pseudo r^2
pR2(full_position)
pR2(main_position)
pR2(elev_position)
pR2(elev_position2)
pR2(elev_position4)
pR2(elev_position5)

#plotting data and values predicted by models
position_data = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("20-25"), each = 50))
position_data2 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("15-20"), each = 50))
position_data3 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("10-15"), each = 50))
position_data4 = data.frame(Position = seq(.2, 1.2, length.out = 50), Block = rep(c("5-10"), each = 50))

plot(Mussel.presence ~ Position, data=ashgrid, pch = 20, col = ashgrid$Block, xlab = "Tidal position (%)", ylab = "Probability of Geukensia demissa occurrence")
legend(.4, 1, unique(ashgrid$Block), col = c("green", "red", "black", "blue"), pch = 20)
text(0.44, 0.78, "Salinity (ppt)")

lines(position_data$Position, predict(elev_position4, newdata=position_data, type='response'),
      col='green')
lines(position_data2$Position, predict(elev_position4, newdata=position_data2, type='response'),
      col='red')
lines(position_data3$Position, predict(elev_position4, newdata=position_data3, type='response'),
      col='black')
lines(position_data4$Position, predict(elev_position4, newdata=position_data4, type='response'),
      col='blue')
```

##NAVD88
```{r pressure, echo=FALSE}
#windows:
ashgrid = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Elevation\\CSV files\\Ash_grids.csv")
#mac:
ashgrid = read.csv("~/Documents/Ribbed mussel/Data/Elevation/CSV files/Ash_grids.csv")
#manipulate data:
ashgrid$Mussel.presence = ifelse(ashgrid$Mussel.presence == 'Present', 1, 0)

site_sal = rev(c(8.35149, 10.96029, 13.86604, 14.23241, 16.46788, 18.12259, 22.67457, 23.05144)) #YOU SHOULD DOUBLE CHECK THESE AND MAKE SURE THEY ARE CALCULATED WELL

ashgrid$salinity = rep(site_sal, each = 30) #salinity at each site is now continuous, based on interpolation from Kelsey's data

#models
navfull_x = glm(Mussel.presence ~ Elevation + salinity, family = binomial, data = ashgrid)
summary(navfull_x)

nav88_x = update(navfull_x, . ~ . - salinity)
nav88_x2 = update(nav88_x, . ~ . + I(Elevation^2))
nav88_x3 = update(nav88_x2, . ~ . + I(Elevation^3))
nav88_x4 = update(nav88_x2, . ~ . + salinity)
nav88_x5 = update(nav88_x4, . ~ . + I(salinity^2))
nav88_x6 = update(nav88_x5, . ~ . - salinity)
nav88_x7 = update(nav88_x5, . ~ . - Elevation)
#getting rid of issue of separation (but also makes model worse):
nav88_x8 = update(nav88_x5, .~. - Elevation)
#interaction:
nav88_int = update(nav88_x4, . ~ . * salinity)
nav88_int2 = update(nav88_x, . ~ . + I(salinity^2))

anova(navfull_x, nav88_x, test='LRT')
AIC(navfull_x, nav88_x)

anova(navfull_x, nav88_x, nav88_x2, nav88_x4, nav88_int, nav88_x5, nav88_int2, test='LRT')
AIC(navfull_x, nav88_x2, nav88_x3, nav88_x4, nav88_x5, nav88_x6, nav88_x7, nav88_x8, nav88_int, nav88_int2) #model 5 is the best, no evidence for interaction

summary(nav88_x5) #has a lower and upper salinity tolerance - just like elevation - which might be why the quadratic equation works better
summary(nav88_x8)

#model fits; pseudo r^2
pR2(navfull_x)
pR2(nav88_x)
pR2(nav88_x2)
pR2(nav88_x4)
pR2(nav88_x5)
pR2(nav88_x6)
pR2(nav88_x8)

#plotting data and values predicted by models
n_sal_bins = 10
min_sal = min(ashgrid$salinity)
max_sal = max(ashgrid$salinity)
x_data = data.frame(Elevation = seq(-0.5, 1, length.out = 50),
                    salinity = rep(seq(min_sal, max_sal,
                                       length.out=n_sal_bins), each = 50))

sal_bins = seq(min_sal, max_sal, length.out = n_sal_bins)
int_col_index = as.numeric(cut(x_data$salinity, sal_bins,
                           include.lowest = T))
obs_col_index = as.numeric(cut(ashgrid$salinity, sal_bins, include.lowest = T))
col_ramp = colorRampPalette(c('blue', 'red'))(length(sal_bins)) 
int_cols = col_ramp[int_col_index]
obs_cols = col_ramp[obs_col_index]

#tiff("Elev.tiff", width = 7, height = 5, units = 'in', res = 300)
par(mfrow=c(1, 1))
plot(jitter(Mussel.presence, .1) ~ Elevation, data=ashgrid, pch = 20,
     col = obs_cols, xlab = "Elevation from NAVD88 (m)", 
     ylab = expression(Probability~of~italic(Geukensia~demissa)~occurrence))
#lines(x_data$MHW, predict(elev_x5, newdata=x_data, type='response'),
#      col= int_cols)
for(i in seq_along(sal_bins)) {
    lines(x_data$Elevation[int_col_index == i], 
          predict(nav88_x5, newdata=x_data[int_col_index == i, ],
                  type='response'), col=col_ramp[i])
}

#95% confidence intervals; messy
ci_dat = predict(nav88_x5, newdata = x_data, type = 'response', se.fit = T)
with(ci_dat, lines(x_data$Elevation, (fit+1.96*se.fit), lty=2))
with(ci_dat, lines(x_data$Elevation, (fit-1.96*se.fit), lty=2))

#dev.off()

#legend
#tiff("Legend.tiff", width = 2, height = 4, units = 'in', res = 300)
legend_image <- as.raster(matrix(int_cols, ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Salinity (???)')
text(x=1.5, y = seq(0,1,l=2), labels = seq(23,8,l=2))
rasterImage(legend_image, 0, 0, 1, 1)
#dev.off()

plot3d(ashgrid$MHW, ashgrid$salinity, ashgrid$Mussel.presence)

x_data$response =  predict(nav88_x5, newdata=x_data, type='response')

which(x_data == max(x_data$response), arr.ind=TRUE)
x_data[337,]

#ROC curve
fit_x = nav88_x5$fitted.values
g_x = roc(Mussel.presence ~ fit_x, data = ashgrid)
plot(g_x)
auc(g_x) #0.87, not too shabby
```