---
title: "Site comparison"
author: "Asa Julien"
date: "February 23, 2017"
output: html_document
---

##Descriptives
```{r, echo=FALSE}
library(dplyr)
library(FSA)
library(nlstools)
library(lattice)
library(ggplot2)
library(lmtest)

std.err = function(x)
  sd(x)/sqrt(length(x))

#windows:
site_compare = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Site comparison\\CSV files\\Comparison.csv")
#mac:
site_compare = read.csv("~/Documents/Ribbed mussel/Data/Site comparison/CSV files/Comparison.csv")

levels(site_compare$Date) = c("February", "May", "August", "November")

#statistical comparisons length, age, density

#length
wilcox.test(Length.mm ~ Status, data = site_compare)
wilcox.test(Length.mm ~ Status, data = site_compare[site_compare$Date == "February",])
wilcox.test(Length.mm ~ Status, data = site_compare[site_compare$Date == "May",])
wilcox.test(Length.mm ~ Status, data = site_compare[site_compare$Date == "August",])
wilcox.test(Length.mm ~ Status, data = site_compare[site_compare$Date == "November",])

#Age
wilcox.test(Growth.bands ~ Status, data = site_compare)
wilcox.test(Growth.bands ~ Status, data = site_compare[site_compare$Date == "February",])
wilcox.test(Growth.bands ~ Status, data = site_compare[site_compare$Date == "May",])
wilcox.test(Growth.bands ~ Status, data = site_compare[site_compare$Date == "August",]) #NSD
wilcox.test(Growth.bands ~ Status, data = site_compare[site_compare$Date == "November",]) #NSD

den_compare = site_compare %>%
  group_by(Status, Quadrat.ID, Date) %>%
  summarise(length(Length.mm) / 0.0625)
colnames(den_compare) = c("Status", "ID", "Date", "Density")

den_aov = aov(Density ~ Status * Date, data = den_compare) #perfect model assumptions; effect of date
summary(den_aov)

#Comparison of harvested, unharvested, and folly sites in a different markdown - maybe just combine everything into a single ANOVA or Kruskal-wallis test in order to avoid multiple comparisons. Be mindful of season.

#general descriptives
mn_lengths = site_compare %>%
  group_by(Status, Date) %>%
  summarise(mean(Length.mm), std.err(Length.mm), mean(na.omit(Growth.bands)), std.err(na.omit(Growth.bands)))

med_lengths = site_compare %>%
  group_by(Status, Date) %>%
  summarise(median(Length.mm), median(na.omit(Growth.bands)))
mn_den = den_compare %>%
  group_by(Status, Date) %>%
  summarise(mean(`length(Length.mm)` / 0.0625), std.err(`length(Length.mm)` / 0.0625))
colnames(mn_den) = c("Status", "Date", "Density", "SE.den")

nr_mussels = site_compare %>%
  group_by(Status) %>%
  summarise(length(Length.mm))

nr_age = site_compare %>%
  group_by(Status) %>%
  summarise(length(na.omit(Growth.bands)))

feb_compare = site_compare[site_compare$Date == "February",]
may_compare = site_compare[site_compare$Date == "May",]
aug_compare = site_compare[site_compare$Date == "August",]
nov_compare = site_compare[site_compare$Date == "November",]

#percent above/below size range
length(site_compare$Length.mm[site_compare$Status == "Harvested" & site_compare$Length.mm >= 76.2])/length(site_compare$Length.mm[site_compare$Status == "Harvested"])
```

##Histograms
```{r, echo=FALSE}
#Histogram for all months
all_hist = ggplot(data = site_compare, aes(x=Length.mm)) + geom_histogram(binwidth = 5) + facet_grid(~Status) + theme_bw() + labs(x="Length (mm)",y="Frequency (number)") + scale_x_continuous(limits = c(0, 130))

all_hist + theme(axis.text = element_text(size=16), axis.title = element_text(size = 20,face = "bold"), strip.text = element_text(size = 18, face = "bold"))

pcent_all = ggplot(data = site_compare, aes(x = Length.mm)) + geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]), binwidth = 5) + facet_grid(.~Status) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)") + scale_x_continuous(limits = c(0, 130)) + scale_y_continuous(limits = c(0, 0.2)) + theme(axis.text = element_text(size=16), axis.title = element_text(size = 20,face = "bold"), strip.text = element_text(size = 18, face = "bold"))

#by season, harvested
ggplot(data = site_compare[site_compare$Status == "Harvested",], aes(x = Length.mm)) + geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Date) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)", title = "Harvested") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = seq(0, 20, 5))

#by season, unharvested
ggplot(data = site_compare[site_compare$Status == "Unharvested",], aes(x = Length.mm)) + geom_histogram(aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Date) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)", title = "Unharvested") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = c(seq(0, 20, 5)))

#both sites, by season
ggplot(data = site_compare, aes(x = Length.mm)) + geom_histogram(data = site_compare[site_compare$Status == "Harvested",], fill = "black", alpha = 0.4, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + geom_histogram(data = site_compare[site_compare$Status == "Unharvested",], fill = "red", alpha = 0.3, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Date) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)", title = "") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = seq(0, 20, 5))

#both sites, feb - may
f_m = site_compare[site_compare$Date != "November",]
f_m = f_m[f_m$Date != "August",] #sloppy but whatever

ggplot(data = f_m, aes(x = Length.mm)) + geom_histogram(data = f_m[f_m$Status == "Harvested",], fill = "black", alpha = 0.4, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + geom_histogram(data = f_m[f_m$Status == "Unharvested",], fill = "red", alpha = 0.3, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Date) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)", title = "") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = seq(0, 20, 5))


#both sites, aug-nov
au_nov = site_compare[site_compare$Date != "May",]
au_nov = au_nov[au_nov$Date != "February",]

ggplot(data = au_nov, aes(x = Length.mm)) + geom_histogram(data = au_nov[au_nov$Status == "Harvested",], fill = "black", alpha = 0.4, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + geom_histogram(data = au_nov[au_nov$Status == "Unharvested",], fill = "red", alpha = 0.3, aes(y=(..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..] * 100), binwidth = 5) + facet_grid(.~Date) + theme_bw() + labs(x = "Length (mm)", y="Frequency (%)", title = "") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_x_continuous(breaks = c(seq(0, 100, 50))) + scale_y_continuous(breaks = seq(0, 20, 5))

#average densities
feb_dens = ggplot(mn_den, aes(x = Status, y = Density, width = 0.5), position="dodge") + facet_grid(~Date)
feb_dens + geom_bar(stat="identity") + geom_errorbar(aes(ymax = Density + SE.den, ymin = Density - SE.den), width = 0.15) + labs(x = expression(Site), y = expression(Density~(individuals~m^{-2}))) + theme(axis.title = element_text(size = 22,face = "bold"), strip.text = element_text(size=20,face = "bold"), axis.text.x = element_text(size=18,face = "bold"), axis.text.y = element_text(size = 15, face = "bold"))
```


##Size at age relationship, unharvested
```{r, echo=FALSE}
#subset the data
harvested.site = site_compare %>%
  select(Status, Date, Length.mm, Growth.bands) %>%
  filter(Status == "Harvested") %>%
  na.omit()

unharvested.site = site_compare %>%
  select(Status, Date, Length.mm, Growth.bands) %>%
  filter(Status == "Unharvested") %>%
  na.omit() 

#estimating parameters
von.length.unharvested = unharvested.site$Length.mm
von.age.unharvested = unharvested.site$Growth.bands
svTypical.unharvested = vbStarts(von.length.unharvested ~ von.age.unharvested, plot = TRUE)
unlist(svTypical.unharvested) 
svTypical.unharvested
von.list.unharvested = list(Linf = 101.72, K = 0.32, t0 = -0.63) #using same Linf variable - CAREFUL
von.list.unharvested

#nls and model
vbTypical.unharvested = von.length.unharvested ~ Linf * (1-exp(-K * (von.age.unharvested - t0)))
fitTypical.unharvested = nls(vbTypical.unharvested, start = svTypical.unharvested)
fitPlot(fitTypical.unharvested, xlab="Number of growth bands", ylab="Length (mm)", main="", cex.axis=1.2, cex.lab=1.4, font.lab=2)
overview(fitTypical.unharvested)
residPlot(fitTypical.unharvested)
hist(residuals(fitTypical.unharvested),main="")
boxplot(Length.mm ~ Growth.bands, data = unharvested.site)

#confidence intervals, unharvested
unharvested_boot = na.omit(unharvested.site[, c(3,4)])
colnames(unharvested_boot) = c("un_Length", "un_Age")
un_formula <- as.formula(un_Length ~ un_Linf * (1 - exp(-un_K * (un_Age - un_t0))))
un_nls1 <- nls(un_formula, start = list(un_Linf = 101.72, un_K = 0.32, un_t0 = -0.63), data = unharvested_boot)
un_strap1 <- nlsBoot(un_nls1, niter = 999)
plot(un_strap1)
plot(un_strap1, type = "boxplot", ask = FALSE)
summary(un_strap1)
confint(un_strap1, plot = TRUE)
htest(un_strap1, "un_K", 0.36, "less") #not sure what this accomplishes

#confidence interval
un_ests = un_strap1$coefboot
ages2plot <- 0:18
fitPlot(fitTypical.unharvested,xlab="Age (growth bands)",ylab="Total Length (mm)",xlim=range(ages2plot), ylim = c(0, 120),main="Unharvested")
LCI <- UCI <- numeric(length(ages2plot))

for (i in 1:length(ages2plot)) {
un_pv <- un_ests[,"un_Linf"]*(1-exp(-un_ests[,"un_K"]*(ages2plot[i]-un_ests[,"un_t0"])))
LCI[i] <- quantile(un_pv,0.025)
UCI[i] <- quantile(un_pv,0.975)
}
lines(UCI~ages2plot,type="l",col="blue",lwd=2,lty=2)
lines(LCI~ages2plot,type="l",col="blue",lwd=2,lty=2)

#predict lengths for age
un_predage = data.frame(von.age.unharvested = rep(seq(0, 15, 1),1))
un_predage$response = predict(fitTypical.unharvested, newdata = un_predage, type = 'reponse')
plot(un_predage$response ~ un_predage$von.age.unharvested)
```

##Size at age relationship, harvested
```{r, echo=FALSE}
#Harvested site
#estimating the parameters (L infinity, K, t0)
von.length.harvested = harvested.site$Length.mm
von.age.harvested = harvested.site$Growth.bands
svTypical.harvested = vbStarts(von.length.harvested ~ von.age.harvested, plot = TRUE)
unlist(svTypical.harvested) 
svTypical.harvested
von.list.harvested = list(Linf = 107.65, K = 0.33, t0 = -0.58) #using same Linf variable - CAREFUL
von.list.harvested

#nls and model
vbTypical.harvested = von.length.harvested ~ Linf * (1-exp(-K * (von.age.harvested - t0)))
fitTypical.harvested = nls(vbTypical.harvested, start = svTypical.harvested)
fitPlot(fitTypical.harvested, xlab="Number of growth bands", ylab="Length (mm)", main="", cex.axis=1.2, cex.lab=1.4, font.lab=2)
overview(fitTypical.harvested)
residPlot(fitTypical.harvested)
hist(residuals(fitTypical.harvested),main="")
boxplot(Length.mm ~ Growth.bands, data = harvested.site)

#confidence intervals, harvested
harvested_boot = na.omit(harvested.site[, c(3,4)])
colnames(harvested_boot) = c("h_Length", "h_Age")
h_formula <- as.formula(h_Length ~ h_Linf * (1 - exp(-h_K * (h_Age - h_t0))))
h_nls1 <- nls(h_formula, start = list(h_Linf = 107.65, h_K = 0.33, h_t0 = -0.58), data = harvested_boot)
h_strap1 <- nlsBoot(h_nls1, niter = 999)
plot(h_strap1)
plot(h_strap1, type = "boxplot", ask = FALSE)
summary(h_strap1)
confint(h_strap1, plot = TRUE)
htest(h_strap1, "h_K", 0.36, "less") #not sure what this accomplishes
h_ests = h_strap1$coefboot
ages2plot <- 0:18
fitPlot(fitTypical.harvested,xlab="Age (growth bands)",ylab="Total Length (mm)",xlim=range(ages2plot),main="Harvested")
LCI <- UCI <- numeric(length(ages2plot))

for (i in 1:length(ages2plot)) {
h_pv <- h_ests[,"h_Linf"]*(1-exp(-h_ests[,"h_K"]*(ages2plot[i]-h_ests[,"h_t0"])))
LCI[i] <- quantile(h_pv,0.025)
UCI[i] <- quantile(h_pv,0.975)
}
lines(UCI~ages2plot,type="l",col="blue",lwd=2,lty=2)
lines(LCI~ages2plot,type="l",col="blue",lwd=2,lty=2)

#predict lengths for age
h_predage = data.frame(von.age.harvested = rep(seq(0, 15, 1),1))
h_predage$response = predict(fitTypical.harvested, newdata = h_predage, type = 'reponse')
plot(h_predage$response ~ h_predage$von.age.harvested)
```

##Comparison of VB equations (just site comparison for now)
```{r, echo=FALSE}
vbLKt = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbLK = Length.mm ~ Linf[Location] * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbLt = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0[Location])))
vbKt = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0[Location])))
vbL = Length.mm ~ Linf[Location] * (1 - exp(-K * (Growth.bands - t0)))
vbK = Length.mm ~ Linf * (1 - exp(-K[Location] * (Growth.bands - t0)))
vbt = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0[Location])))
vb0 = Length.mm ~ Linf * (1 - exp(-K * (Growth.bands - t0)))

#starting values. They are fairly similar so I'm going to use the same for each group (pooled).
sv0 = vbStarts(Length.mm ~ Growth.bands, data = site_compare)
svLKt = Map(rep, sv0, c(2,2,2))

#fit model
fitLKt = nls(vbLKt, data = site_compare, start = svLKt)
residPlot(fitLKt, col = rgb(0, 0, 0, 1/3))

fit0 = nls(vb0, data = site_compare, start = sv0)
residPlot(fit0)

lrt(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ") #Differences!
extraSS(fit0, com = fitLKt, com.name = "All param differ", sim.names = "No param differ")

#differences in nested models
svLK = Map(rep, sv0, c(2,2,1))
svLt = Map(rep, sv0, c(2,1,2))
svKt = Map(rep, sv0, c(1,2,2))

fitLK = nls(vbLK, data = site_compare, start = svLK)
fitLt = nls(vbLt, data = site_compare, start = svLt)
fitKt = nls(vbKt, data = site_compare, start = svKt)

lrt(fitLK,fitLt,fitKt,com=fitLKt,com.name="All param diff",
sim.names=c("Linf,K diff","Linf,t0 diff","K,t0 diff"))

#next subsets compared to fitLK, highest loglikelihood
svL = Map(rep, sv0, c(2,1,1))
svK = Map(rep, sv0, c(1,2,1))
fitL = nls(vbL, data = site_compare, start = svL)
fitK = nls(vbK, data = site_compare, start = svK)

lrt(fitL,fitK,com=fitLK,com.name="Linf,K dif",
sim.names=c("Linf dif","K dif")) #Linf differs but K does not

lrt(fitL,fitK,com=fitLKt,com.name="Linf,K,t dif",
sim.names=c("Linf dif","K dif")) #JUST Linf DIFFERS

#final check:
lrt(fit0, com = fitL,com.name = "Linf dif", sim.names = "No param dif")

#all together now
svt = Map(rep, sv0, c(1,1,2))
fitt = nls(vbt, data = site_compare, start = svt)

cbind(AIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0),
BIC(fitLKt,fitLK,fitLt,fitKt,fitL,fitK,fitt,fit0)) #Just different L inf seems to be the best model I think
```

sssss