---
title: "Harvesting practices"
author: "Asa Julien"
date: "October 5, 2017"
output: html_document
---

##Biomass
```{r}
library(ggplot2)
library(dplyr)
library(FSA)
library(MASS)

#windows:
biomass = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Harvesting practices\\CSV files\\mass.csv")
#mac:
biomass = read.csv("~/Documents/Ribbed mussel/Data/Harvesting practices/CSV files/mass.csv")
biomass$Block = as.factor(biomass$Block)

std.err = function(x)
  sd(x)/sqrt(length(x))

biomass = biomass[biomass$Notes != "Wet",]
mass_aov = aov(log(Weight + 1) ~ Treatment + Block, data = biomass)
stepAIC(mass_aov)
detach("package:MASS", unload = T)
mass_aov = aov(log(Weight + 1) ~ Treatment, data = biomass)
summary(mass_aov)
TukeyHSD(mass_aov)
plot(mass_aov)
shapiro.test(mass_aov$residuals)

krusk_mass = kruskal.test(Weight ~ Treatment, data = biomass)
krusk_mass
dunnTest(Weight ~ Treatment, data = biomass)

av_mass = biomass %>%
  group_by(Treatment)%>%
  select(Block, Treatment, Weight) %>%
  summarise(mean(Weight), std.err(Weight))
colnames(av_mass) = c("Treatment", "Wt", "se.wt")
av_mass$Treatment = factor(av_mass$Treatment, levels = c("Control", "Partial", "Full"))

p_mass = ggplot(av_mass, aes(Treatment, Wt))
aaa1 = p_mass + geom_bar(stat = "identity", width = 0.7, fill = 1) + geom_errorbar(aes(ymin = Wt - se.wt, ymax = Wt + se.wt), width = 0.1) + labs(x = "", y = expression(Aboveground~italic(S.~alterniflora)~biomass~(g))) + annotate("text", x = "Full", y = 62, label = "*", size = 10)  + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 13), strip.text = element_text(size = 13), axis.text.x = element_text(size=13, colour = "black"), axis.text.y = element_text(size = 15, colour = "black"), axis.title.y = element_text(size = 10)) + scale_y_continuous(limits = c(0,120), expand = c(0,0))

#Conclusion: After a full year, biomass in Full harvest plots was significantly lower than both control and partially harvested plots (ANOVA, Tukey's HSD, and Kruskal test). Partially harvested plots displayed an intermediate response. Samples that were partially damp were removed from analysis.
```

##Stems
```{r}
#windows:
stems = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Harvesting practices\\CSV files\\Stems.csv")
#mac:
stems = read.csv("~/Documents/Ribbed mussel/Data/Harvesting practices/CSV files/Stems.csv")

stems$Treatment = factor(stems$Treatment, levels = c("Control", "Partial", "Full"))
stems$Block = as.factor(stems$Block)

#density
stemdensity = stems %>%
  group_by(Treatment, Block) %>%
  select(Block, Treatment, Length) %>%
  summarise(length(Length))
colnames(stemdensity) = c("Treatment", "Block", "Density")
stemdensity$Treatment = factor(stemdensity$Treatment, levels = c("Control", "Partial", "Full"))

dens_glm = aov(log(Density+1) ~ Treatment, data = stemdensity) #no effect of block
summary(dens_glm)
plot(dens_glm)
#no differences; may be due to outliers though

stem_mn = stemdensity %>%
  group_by(Treatment) %>%
  summarise(mean(Density), std.err(Density))
colnames(stem_mn) = c("Treatment", "mn_dens", "se_dens")

aaa2 = ggplot(stem_mn, aes(Treatment, mn_dens)) + geom_bar(stat = "identity", width = 0.7, fill = 1) + geom_errorbar(aes(ymin = mn_dens - se_dens, ymax = mn_dens + se_dens), width = 0.1) + labs (x = "Harvest treatment", y = expression(Number~of~stems~per~0.0625~m^2)) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=13, colour = "black"), axis.text.y = element_text(size = 15, colour = "black"), axis.title.y = element_text(size = 10)) + scale_y_continuous(breaks = c(0,5,10,15,20,25,30,35), limits = c(0,35), expand = c(0,0))

#length
ln_krusk = kruskal.test(Length ~ Treatment, data = stems)
ln_krusk
dunnTest(Length ~ Treatment, data = stems)

plot(Length ~ Treatment, xlab = "", ylab = "Length (mm)", data = stems)
aaa3 = ggplot(stems, aes(y = Length, x = Treatment)) + geom_boxplot() + labs(x = "Harvest treatment", y = expression(italic(S.~alterniflora)~stem~length~(mm))) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=13, colour = "black"), axis.text.y = element_text(size = 15, colour = "black"), axis.title.y = element_text(size = 10)) + scale_y_continuous(limits = c(0,1500), expand = c(0,0))

#percentage of larger stems
hist(stems$Length, breaks = 20)
stem_cent = stems %>%
  group_by(Treatment) %>%
  select(Treatment, Length) %>%
  summarise(length(Treatment[Length > 500])/length(Treatment)) #kind of arbitrary

#Conclusion: no difference in median stem length between treatments

#%flowering
flowering = stems %>%
  group_by(Treatment, Block) %>%
  select(Block, Treatment, Flowering) %>%
  summarise(sum(Flowering)/length(Flowering))
colnames(flowering) = c("Treatment", "Block", "Flower")
flowering$Treatment = factor(flowering$Treatment, levels = c("Control", "Partial", "Full"))

flower_mn = flowering %>%
  group_by(Treatment) %>%
  summarise(mean(Flower) * 100, std.err(Flower) * 100)
colnames(flower_mn) = c("Treatment", "mn_flower", "se_flower")

aaa4 = ggplot(flower_mn, aes(Treatment, mn_flower)) + geom_bar(stat = "identity", width = 0.7, fill = 1) + geom_errorbar(aes(ymin = mn_flower - se_flower, ymax = mn_flower + se_flower), width = 0.1) + ylab("Percent of stems flowering") + xlab("") + annotate("text", x = "Full", y = 9.5, label = "*", size = 10) + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=13, colour = "black"), axis.text.y = element_text(size = 15, colour = "black"), axis.title.y = element_text(size = 10)) + scale_y_continuous(limit = c(0,25), breaks = c(0,5,10,15,20,25), expand = c(0,0))

flower_aov = aov(asin(sqrt(Flower)) ~ Treatment + Block, data = flowering) #transformed data
require(MASS)
stepAIC(flower_aov)
detach("package:MASS", unload = T)
flower_aov = aov(asin(sqrt(Flower)) ~ Treatment, data = flowering)
summary(flower_aov)
TukeyHSD(flower_aov)
plot(flower_aov)
#Conclusion: percent of stems flowering is lower in fully harvested plots than in the control. The partial harvest displays an intermediate response.
```

##Recruitment and size
```{r}
#windows:
recruits = read.csv("C:\\Users\\juliena\\Desktop\\Data\\Harvesting practices\\CSV files\\sizeage.csv")
#mac:
recruits = read.csv("~/Documents/Ribbed mussel/Data/Harvesting practices/CSV files/sizeage.csv")

recruits$Block = as.factor(recruits$Block)

yoty = recruits %>%
  group_by(Block, Treatment) %>%
  select(Block, Treatment, Length, Bands) %>%
  summarise(length(Bands[Bands == 0]), length(Bands)) #nothing with 1 growth band
colnames(yoty) = c("Block", "Treatment", "Recruits", "All")
yoty$Treatment = factor(yoty$Treatment, levels = c("Control", "Partial", "Full"))

sum(yoty$Recruits)/sum(yoty$All)
#could use predicted size based on age to determine who's a recruit (42.9 mm for 1 growth band)

#quick presence-absence
yoty$y_n = ifelse(yoty$Recruits == 0, 0, 1)

recruits_logr = glm(y_n ~ Treatment, data = yoty, family = binomial)
summary(recruits_logr) #very similar post hoc to poisson

#count data
recruits_glm = glm(Recruits ~ Treatment, data = yoty, family = poisson)
summary(recruits_glm) #no overdispersion? or very slight

1 - pchisq(summary(recruits_glm)$deviance, 
           summary(recruits_glm)$df.residual
           )

library(multcomp)
summary(glht(recruits_logr, mcp(Treatment="Tukey")))
summary(glht(recruits_glm, mcp(Treatment="Tukey"))) #similar. something is weird with all zeroes though... says it's not significantly different.
detach("package:multcomp", unload = T)
detach("package:TH.data", unload=T)
detach("package:MASS", unload = T)


ggplot(yoty, aes(Recruits, fill = Treatment)) + geom_histogram(binwidth = 0.5, position = "dodge") + xlab(expression(Number~of~italic(Geukensia~demissa)~recruits)) +theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_y_continuous(expand = c(0,0),name = "Count") + scale_fill_grey(start = 0, end = .9)

ggplot(yoty, aes(Treatment, Recruits)) + geom_bar(stat = "identity", width = 0.5) + scale_y_continuous("Number of recuits", breaks = seq(0, 12, 4)) + xlab("Harvest treatment") + theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + theme(axis.title = element_text(size = 15), strip.text = element_text(size = 15), axis.text.x = element_text(size=15), axis.text.y = element_text(size = 15)) + scale_y_continuous(expand = c(0,0), name = expression(Number~of~italic(Geukensia~demissa)~recruits))

with(recruits, hist(Length, breaks = 50))
with(recruits[recruits$Treatment == "Control",], hist(Length, breaks = 50))
with(recruits[recruits$Treatment == "Partial",], hist(Length, breaks = 50))
with(recruits[recruits$Treatment == "Full",], hist(Length, breaks = 50))

#When both 0 and 1-growth band individuals are included in the analysis, there are significant differences in number of recruits between each treatment; controls has the most, full the least. Partial is intermediate. When only age 0 mussels are considered, partial & full harvest become the same essentially (no recruitment, except for 1), and control still has the most recruits


#All of the plotssss 7:7 ratio
plot_grid(aaa1, aaa4, aaa2, aaa3, labels = "AUTO", label_x = 0.01, align = "v", ncol = 2)
```
